### PR TITLE
fix: add new combined icon component to render double icon assets in one

### LINKED ISSUE #10373: Add a combined mode for dual icon assets so we don't break UI in spots
# Summary

Some of our assets like WETH/FOX have a dual icon which regularly breaks UI elements. Even when it doesn't break stuff if breaks alignment. Few examples below

Create a combined mode that we can render in cases where the side by side is going to break stuff.

# AC

It should just be a split like this

### PR DESCRIPTION
**Pull request by premiumjibles**
## Description

Currently our side by side asset breaks our components or our alignment semi regularly. 

Discord thread here https://discord.com/channels/554694662431178782/1410133120639959090

E.g.

image

image

This PR combined the two into a split single icon.

## Issue (if applicable)

closes #10373

## Risk

Low risk, double icon components are already pretty edge case. This could render our combined icon where maybe we don't want it to?

> High Risk PRs Require 2 approvals

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

## Testing

* Test that dual icon assets combine in areas where alignment matters (e.g. list scenarios)
* Test that dual icon assets collapse in scenarios with limited space (e.g. asset row)
* Test that other icons are not effected

### Operations

- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)

https://jam.dev/c/fbe70342-3a49-4403-9075-c983621e15a0

## Summary by CodeRabbit

- New Features
  - Improved two-asset pair display with a vertical split for clearer identification.

- Refactor
  - Unified icon rendering across transactions, notifications, listings, and menus for more consistent visuals and reduced re-renders.
  - Simplified pairing behavior for single, two, and multi-asset displays.

- Breaking Changes
  - Removed legacy paired-icon configuration affecting some card and icon components' props.

### CODE REVIEW

File: src/features/defi/components/PairIcons/PairIcons.tsx [hunk 1]
```diff
@@ -105,10 +109,35 @@ export const PairIcons = ({
 
   if (!icons?.length) return null
 
+  // Combined mode for exactly 2 icons
+  if (icons.length === 2) {
```
Comment (NeOMakinG) [inline src/features/defi/components/PairIcons/PairIcons.tsx]: Are we sure we want a fix for only this count? multiple icons will have the same issue than 2 icons as it will show a +X round

image
 
 In this case the layout will also be weird

Comment (twblack88) [reply src/features/defi/components/PairIcons/PairIcons.tsx]: if above 2 icons, we should just show the number icon count with no split. balancer has always done great designing for these use cases. 

We could consider a fancy toggle where if you hit the numbers icon it expands a nested tag with like however many assets are in the pool like this:
Screenshot 2025-08-28 at 10 59 23 AM

tap to expand basically. 

the downside is, of course, doing this on an already expanding row. So we can ticket that experience for the asset itself, since portals keeps throwing these wild multi asset things at us.

**Comment by premiumjibles** [comment]
@twblack88 @reallybeard @NeOMakinG To keep things really simple i've just kept the existing behaviour of 3+ icons where it creates the blurry circle. Except i've removed the option to "show first" which makes it side by side (too wide). I've also added an on hover (on click on mobile) to view the assets included.

https://jam.dev/c/9df6843f-b0bc-46da-a4cb-e4a2a0d26211

https://github.com/shapeshift/web/pull/10356/commits/27ec0750acae315a08aa1bbc95917c72d85a5a07

Then just a bit of structural cleanup based on new logic to make the flow super clear https://github.com/shapeshift/web/pull/10356/commits/75436b51d0051cfc861ada3d215d8fba42043cf5

File: src/features/defi/components/PairIcons/PairIcons.tsx (hunk 1 above)
Comment (premiumjibles) [reply src/features/defi/components/PairIcons/PairIcons.tsx]: Actioned

**Review by 0xApotheosis — APPROVED** [review]
This is so damn tidy, nice one @premiumjibles.

Tested on responsive mobile, native mobile, and desktop views, all working as expected.

Get in!
