### PR TITLE
fix: update onramper params

### LINKED ISSUE #9705: OnRamper Off-Ramping Mode Updating
Currently when trying to off ramp using onramper, we have them exit to onramper to the buy crypto side instead of the sell option. @reallybeard said this is a simple mode we need to designate

### PR DESCRIPTION
**Pull request by reallybeard**
## Description

This updates the params to reflect what the widget actually supports.

Changes supportsSell to `mode`

Removed other params that are no longer supported.

## Issue (if applicable)

closes #9705 

## Risk

> High Risk PRs Require 2 approvals

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

### Operations

- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

Clicking on-ramper from the sell screen takes you to on-ramper in the sell mode.

Clicking on-ramper from the buy screen takes you to the buy mode

## Screenshots (if applicable)
Screenshot 2025-06-16 at 11 16 35 AM

### CODE REVIEW

File: src/components/Modals/FiatRamps/fiatRampProviders/onramper.ts [hunk 1]
```diff
@@ -197,13 +197,9 @@ export const createOnRamperUrl = async ({
 
   if (action === FiatRampAction.Sell) {
     // Note: selling via OnRamper does not allow selecting the currency, their api currently does not support it
-    params.set('initScreen', 'sell')
-    params.set('supportSell', 'true')
-    params.set('isAddressEditable', 'true')
```
Comment (gomesalexandre) [inline src/components/Modals/FiatRamps/fiatRampProviders/onramper.ts:202]: Confirmed gone https://docs.onramper.com/docs/supported-widget-parameters

File: src/components/Modals/FiatRamps/fiatRampProviders/onramper.ts [hunk 2]
```diff
@@ -197,13 +197,9 @@ export const createOnRamperUrl = async ({
 
   if (action === FiatRampAction.Sell) {
     // Note: selling via OnRamper does not allow selecting the currency, their api currently does not support it
-    params.set('initScreen', 'sell')
-    params.set('supportSell', 'true')
```
Comment (gomesalexandre) [inline src/components/Modals/FiatRamps/fiatRampProviders/onramper.ts:201]: Confirmed gone https://docs.onramper.com/docs/supported-widget-parameters

File: src/components/Modals/FiatRamps/fiatRampProviders/onramper.ts [hunk 3]
```diff
@@ -197,13 +197,9 @@ export const createOnRamperUrl = async ({
 
   if (action === FiatRampAction.Sell) {
     // Note: selling via OnRamper does not allow selecting the currency, their api currently does not support it
-    params.set('initScreen', 'sell')
```
Comment (gomesalexandre) [inline src/components/Modals/FiatRamps/fiatRampProviders/onramper.ts:200]: Confirmed gone https://docs.onramper.com/docs/supported-widget-parameters
