### PR TITLE
fix: explore page performance

### LINKED ISSUE #10580: Fix caching on explore mobile
## Context \[Author\]

Explore page on mobile is slow, we should explore caching or pre-fetching to make it faster. 

For pill categories and all categories we should make sure that there are 5 assets or more, or understand why that's not possible. E.g., liquid staking which seems off.

### Reproduction \[Author\]

Explore page categoreis need a little love.

## Screenshots, video  \[Author\]

[ScreenRecording_09-18-2025 11-29-36_1.MP4](https://uploads.linear.app/ed5193d7-27ef-4be2-b461-c7791d75bc4f/f4c18487-3b36-4348-a685-14587b1017d8/a7343d01-49ba-481b-b697-8af9c1cc557e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2VkNTE5M2Q3LTI3ZWYtNGJlMi1iNDYxLWM3NzkxZDc1YmM0Zi9mNGMxODQ4Ny0zYjM2LTQzNDgtYTY4NS0xNDU4N2IxMDE3ZDgvYTczNDNkMDEtNDliYS00ODFiLWI2OTctOGFmOWMxY2M1NTdlIiwiaWF0IjoxNzU4MjIwNTU2LCJleHAiOjMzMzI4NzgwNTU2fQ.C4vpCScf_qyDTS_TZGNWkAe2gCUuKIVjAxm_A8nS4lo)

### AC

* Spike on pre fetch, caching, or some other fancy optimistic rendering we can use to get these pages feeling more responsive. 
  * could even render one at a time and an expanding list.
* From understanding check on each category type, check on the thin "pill" categories (liquid staking, RWA)

## Rough how to fix \[Eng\]

> Breakdown a path to solve for acc or any reference material, docs. A place for estimation notes or initial comments for solutions.

### LINKED ISSUE #10624: Fix Explore loading slowly
## Context \[Author\]

Investigate the main thread to see why the explorer page loads slowly.

### Reproduction \[Author\]

open explore, especially on android.

## Screenshots, video  \[Author\]

[ScreenRecording_09-18-2025 11-29-36_1.MP4](https://uploads.linear.app/ed5193d7-27ef-4be2-b461-c7791d75bc4f/f4c18487-3b36-4348-a685-14587b1017d8/a7343d01-49ba-481b-b697-8af9c1cc557e?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2VkNTE5M2Q3LTI3ZWYtNGJlMi1iNDYxLWM3NzkxZDc1YmM0Zi9mNGMxODQ4Ny0zYjM2LTQzNDgtYTY4NS0xNDU4N2IxMDE3ZDgvYTczNDNkMDEtNDliYS00ODFiLWI2OTctOGFmOWMxY2M1NTdlIiwiaWF0IjoxNzU4NTc1Njc4LCJleHAiOjMzMzI5MTM1Njc4fQ.4VPc_yjsf5VuZ0lQS29NTQEiKbWPxsNgBZXa89U7wA4)

### AC

Depending on if we cache in [SS-4928](https://linear.app/shapeshift-dao/issue/SS-4928/fix-caching-on-explore-mobile)

## Rough how to fix \[Eng\]

> Breakdown a path to solve for acc or any reference material, docs. A place for estimation notes or initial comments for solutions.

### PR DESCRIPTION
**Pull request by NeOMakinG**
## Description

Improve the explore page performances by:
- Avoid running query selectors if the component isn't rendered/enabled
- Prefetching coingecko requests so category pages are instantly loading
- Rendering and fetching data only if they are inside the viewport

While at it:
- Properly ordering market cap card + category by market cap
- Properly fetching portals market data using portals provider instead of coingecko (market data was borken because of that)
- content shifts caused by wrong heights of carrousel dots and skeletons

Do not touch at portals bits as it's quite sensible with the rate limiting things, we will need another issue to fix that, we need a proxy that would use another API key to be able to pre-fetch categories as well as avoiding rate limiting

## Issue (if applicable)

closes #10624
closes #10580

## Risk
Low
> High Risk PRs Require 2 approvals

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

## Testing
- Try to go back and forth with the explore page on mobile (using expo or deploying on an ephemeral env), main thread should be faster (not blocked anymore on my phone...)
- Try to click on any category page, assets should be preloaded (minus portals which isn't doable considering we have rate limit issues, we need a proxy for that, using a different API key, so we can prefetch all categories in a server and avoid spamming their API)
-- Notice if you click too fast, skeletons can be there because the request can take a little bit of time
- Notice way less skeletons on back and forth as we are not reacting anymore on both portals and coingecko queries for every cards/categories + notice no more content shifts when going back from a category page to the explore page

Notice portal categoires might be rate limited due to to the provider market data order change, we need to tackle that with a proxy in another issue!

### Operations

- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)
https://jam.dev/c/a49036cc-9a11-4752-b4a4-ade2c2727c90

## Summary by CodeRabbit

- New Features
  - Background prefetching of Explore categories; Markets supports paginated loading for faster browsing.

- Performance
  - Category cards defer fetching until visible and use larger skeletons for smoother scrolling.
  - Coingecko market data is cached to reduce redundant requests.
  - Pricing sources prioritized for more consistent pool asset prices.

- Bug Fixes
  - Carousel controls and dot indicators display reliably with consistent spacing.
  - Simplified loading logic reduces flicker in Explore and category views.

### CODE REVIEW

File: src/components/Carousel/Carousel.tsx [hunk 1]
```diff
@@ -139,7 +139,7 @@ export const Carousel = ({
             {renderSlides}
           </Box>
         </Box>
-        {(showDots || showArrows) && scrollSnaps.length > 1 && (
+        {(showDots || showArrows) && (
```
Comment (gomesalexandre) [inline src/components/Carousel/Carousel.tsx:142]: q: what does dis do?

File: src/lib/market-service/market-service-manager.ts [hunk 2]
```diff
@@ -73,10 +73,25 @@ export class MarketServiceManager {
...
+
+      const asset = assets[assetId]
+
+      // Portals is prioritized when finding by AssetId, as it has more reliable data for LP tokens
+      const prioritizedProviders = asset?.isPool
+        ? [
+            ...(portalsProvider ? [portalsProvider] : []),
+            ...this.marketProviders.filter(provider => !(provider instanceof PortalsMarketService)),
+          ]
+        : this.marketProviders
```
Comment (gomesalexandre) [inline src/lib/market-service/market-service-manager.ts:91]: 💜

File: src/pages/Explore/components/CategoryCard.tsx [hunk 3]
```diff
@@ -1,7 +1,8 @@
 import { Box, Button, Flex, Skeleton, Text as CText, useColorModeValue } from '@chakra-ui/react'
-import type { Asset } from '@shapeshiftoss/types'
 import range from 'lodash/range'
+import type { Asset } from 'packages/types/src/base'
```
[the remark this answers is not in the document]
Comment (gomesalexandre) [reply src/pages/Explore/components/CategoryCard.tsx]: Totally valid commen, LSP rug

File: src/pages/Explore/components/CategoryCard.tsx [hunk 4]
```diff
@@ -48,9 +53,15 @@ export const CategoryCard = memo(
       isLoading: isCategoryQueryDataLoading,
       isError: isCategoryQueryDataError,
     } = categoryHook({
-      enabled: category !== MarketsCategories.OneClickDefi,
+      enabled: category !== MarketsCategories.OneClickDefi && inView,
```
Comment (gomesalexandre) [inline src/pages/Explore/components/CategoryCard.tsx:56]: 💜

File: src/pages/Explore/Explore.tsx [hunk 5]
```diff
@@ -91,6 +92,8 @@ export const Explore = memo(() => {
   const isRfoxFoxEcosystemPageEnabled = useFeatureFlag('RfoxFoxEcosystemPage')
   const assetActionsDrawer = useModal('assetActionsDrawer')
 
+  usePrefetchExploreCategories()
```
Comment (gomesalexandre) [inline src/pages/Explore/Explore.tsx:95]: 🧠

File: src/pages/Markets/hooks/useCoingeckoData.ts [hunk 6]
```diff
@@ -153,7 +153,9 @@ export const useTopMoversQuery = ({
     queryFn: enabled ? getCoingeckoTopMovers : skipToken,
     staleTime: Infinity,
     select: data =>
-      selectCoingeckoAssetIdsSortedAndOrdered(data, dispatch, assets, sortBy, orderBy),
+      enabled
+        ? selectCoingeckoAssetIdsSortedAndOrdered(data, dispatch, assets, sortBy, orderBy)
+        : undefined,
```
Comment (gomesalexandre) [inline src/pages/Markets/hooks/useCoingeckoData.ts:170]: q: do we need this i.e is it because of stale data and this recomputing, despite not enabled?

Feels like this should be referentially stable even in this case, but obviously doesn't hurt, just feels off

File: src/pages/Explore/hooks/usePrefetchExploreCategories.ts [hunk 7]
```diff
@@ -0,0 +1,47 @@
...
+      queryFn: getCoingeckoTopMovers,
+      staleTime: Infinity,
+    })
+
+    queryClient.prefetchQuery({
+      queryKey: ['coinGeckoRecentlyAdded', OrderDirection.Descending, SortOptionsKeys.Volume],
+      queryFn: getCoingeckoRecentlyAdded,
+      staleTime: Infinity,
+    })
+
```
[the remark this answers is not in the document]
Comment (gomesalexandre) [reply src/pages/Explore/hooks/usePrefetchExploreCategories.ts:39]: Confirmed valid - this won't do what we think it does 

Image
Image

File: src/pages/Explore/hooks/usePrefetchExploreCategories.ts [hunk 8]
```diff
@@ -0,0 +1,47 @@
...
+    const marketCapDescOrder: CoinGeckoSortKey = 'market_cap_desc'
+    queryClient.prefetchQuery({
+      queryKey: ['coinGeckoMarkets', OrderDirection.Descending, 1, 10],
+      queryFn: () => getCoingeckoMarkets(marketCapDescOrder, undefined, undefined),
+      staleTime: Infinity,
```
[the remark this answers is not in the document]
Comment (gomesalexandre) [reply src/pages/Explore/hooks/usePrefetchExploreCategories.ts]: Valid comment: this will use default `100`

Image

But then actual fetch will use 10 

Image

File: src/pages/Explore/components/CategoryCard.tsx (hunk 3 above)
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply src/pages/Explore/components/CategoryCard.tsx]: Makes sense, changed in next commit

File: src/pages/Explore/hooks/usePrefetchExploreCategories.ts (hunk 7 above)
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply src/pages/Explore/hooks/usePrefetchExploreCategories.ts:39]: Seems right, changed in next commit but I need to test and verify it works properly

File: src/pages/Explore/hooks/usePrefetchExploreCategories.ts (hunk 8 above)
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply src/pages/Explore/hooks/usePrefetchExploreCategories.ts]: Removed in next commit

File: src/pages/Markets/hooks/useCoingeckoData.ts (hunk 6 above)
Comment (NeOMakinG) [reply src/pages/Markets/hooks/useCoingeckoData.ts:170]: Yep this is recomputing even if the query is disabled, it was causing some slow downs even when we were not needing this data

File: src/components/Carousel/Carousel.tsx (hunk 1 above)
Comment (NeOMakinG) [reply src/components/Carousel/Carousel.tsx:142]: It always shows the dot bar (pagination bar) even if there are no element yet, if we don't show it, we will have some layout shifts because the height will come after the first load, this ensure we always have the place for this element so it doesn't cause layout shift

**Comment by NeOMakinG** [comment]
> * https://jam.dev/c/228d697a-ab31-436b-bd49-b192be3eefdd

It should be better now after [315c045](https://github.com/shapeshift/web/pull/10645/commits/315c045d55e914c0d714c7f5ee1151eec908bb00)

- XHR are leveraging 250 assets always as it's already fetched on load, shared with tanstack query so we don't duplicate requests

I gave a try to reduce our XHRs for individual tokens in [4aed5a3](https://github.com/shapeshift/web/pull/10645/commits/4aed5a31227d4ca6ed1c56217c8cdda929d71cfc)

I've been able to reduce it by 10 XHRs, from 158 in production to 148 here, by mainly not fetching any coingecko tokens we already have, but any tokens that are not a part of our asset slice should be fetched because markets/trending/movers queries doesn't have the necessary information to know if it's an asset we shouldn't add (chain support or anything else)

That said we need to keep individual tokens calls for assets we absoluletly don't know... to verify if we add to add them to our slice or if they are assets we don't support

File: src/lib/coingecko/types.ts [hunk 9]
```diff
@@ -72,7 +72,7 @@ export type RecentlyAddedResponse = RecentlyAddedCoin[]
 
 export type CoingeckoAsset = {
   assetId: AssetId
-  details: CoingeckoAssetDetails
+  details?: CoingeckoAssetDetails
 }
```
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply src/lib/coingecko/types.ts:76]: We are already early returning if details isn't defined?

File: src/pages/Markets/hooks/useCoingeckoData.ts (hunk 6 above)
Comment (gomesalexandre) [reply src/pages/Markets/hooks/useCoingeckoData.ts:170]: Not a blocker by any means and could be a follow-up but couldn't we stabilise selectors to ensure no rerenders? e.g instead of `selectCoingeckoAssetIdsSortedAndOrdered(data, dispatch, assets, sortBy, orderBy)`, make a memoized lambda on the most stable subset of `data, dispatch, assets, sortBy, orderBy` (probably without `assets` ?), and then access assets as-needed with `store.getState()` in the function itself.

Having the function reusable is good, but gut feel is if we lamba it, it would become stable and not re-run.
Also if we want to go one deeper, we could memoize the whole args of of `useQuery(queryArgs)` .

See https://tanstack.com/query/latest/docs/framework/react/guides/query-functions#query-function-variables

File: src/lib/coingecko/utils.ts [hunk 10]
```diff
@@ -47,7 +49,27 @@ const getCoinDetails = async (
   i: number,
   all: CoingeckoAsset[],
 ) => {
+  const assets = selectAssets(store.getState())
+
   try {
+    // First, try to get asset IDs using the adapter
+    const assetIds = adapters.coingeckoToAssetIds(marketCap.id)
```
Comment (gomesalexandre) [inline src/lib/coingecko/utils.ts:56]: eyy 🧠

File: src/lib/coingecko/utils.ts [hunk 11]
```diff
@@ -47,7 +49,27 @@ const getCoinDetails = async (
...
+
+    if (assetIds && assetIds.length > 0) {
+      // Check if we already have this asset in our store
```
Comment (gomesalexandre) [inline src/lib/coingecko/utils.ts]: nitpick: not really a store, it's in-memory data but that works!

File: src/lib/coingecko/utils.ts (hunk 10 above)
Comment (gomesalexandre) [reply src/lib/coingecko/utils.ts:56]: also q: do we need any kind of migration re: this?

File: src/lib/coingecko/utils.ts [hunk 12]
```diff
@@ -137,9 +159,16 @@ export const getCoingeckoMarketsRaw = async (
...
-  )
+  const data = await queryClient.fetchQuery({
+    queryKey: ['coingeckoMarketsRaw', order, page, pageSize],
+    queryFn: async () => {
+      const { data } = await axios.get<CoinGeckoMarketCap[]>(
+        `${coingeckoBaseUrl}/coins/markets?vs_currency=usd&order=${order}&per_page=${pageSize}&page=${page}&sparkline=false`,
+      )
+      return data
+    },
+    staleTime: Infinity,
```
Comment (gomesalexandre) [inline src/lib/coingecko/utils.ts:170]: q: will this break market-data refetch?

File: src/pages/Markets/hooks/useCoingeckoData.ts [hunk 13]
```diff
@@ -38,6 +38,18 @@ const selectCoingeckoAssets = (
       const assetId = topMover.assetId
       const chainId = fromAssetId(assetId).chainId
       const feeAsset = selectFeeAssetById(store.getState(), assetId)
+
+      // Handle optional details - if we don't have details, we already have the asset
```
Comment (gomesalexandre) [inline src/pages/Markets/hooks/useCoingeckoData.ts:42]: q: not sure I understand this one - is this correct?

File: src/lib/coingecko/utils.ts (hunk 10 above)
Comment (NeOMakinG) [reply src/lib/coingecko/utils.ts:56]: Nothing related with a migration here, it just avoid fetching coingecko details if we already have their market data/assetId

File: src/lib/coingecko/utils.ts (hunk 12 above)
Comment (NeOMakinG) [reply src/lib/coingecko/utils.ts:170]: Market data refetch is using the market service, which doesn't have the staletime, following my tests I didn't find any issues with that

image


I can see all the refresh coming every X seconds

File: src/pages/Markets/hooks/useCoingeckoData.ts (hunk 13 above)
Comment (NeOMakinG) [reply src/pages/Markets/hooks/useCoingeckoData.ts:42]: `details` is a coingecko thing, if we don't have those details it means we already have the market data in the store, because `getCoinDetails` didn't return the coingecko details but the assetId only as he didn't have to fetch the details (reducing XHR)

File: src/lib/coingecko/utils.ts (hunk 11 above)
Comment (NeOMakinG) [reply src/lib/coingecko/utils.ts]: Changed in [3ed3dc7](https://github.com/shapeshift/web/pull/10645/commits/3ed3dc7d5e66b4ff542a91a4fc39793820dff88d)

File: src/pages/Markets/hooks/useCoingeckoData.ts (hunk 6 above)
Comment (NeOMakinG) [reply src/pages/Markets/hooks/useCoingeckoData.ts:170]: Why not in a follow up if we have the time for it but for now at least it works as expected 🙏
