### PR TITLE
fix(TransactionHistory): don't display receive Tx fees

### LINKED ISSUE #1239: bug - cosmos tx history does not show symbol with fee
note ethereum tx's show ETH next to the fee, atom tx's do not

image

### PR DESCRIPTION
**Pull request by gomesalexandre**
## Description

This hides miner fees for receive Txs in TransactionHistory.

Currently, fees are displayed for receive Txs in the Transaction History section but we shouldn't display them, as unchained is not returning us fees for receive txs, which results in unwanted behavior where we're not able to surface the symbol. Confirmed with @kaladinlight that's the correct unchained behavior.

Not displaying Tx fees is also the current behavior in the Transactions section in dashboard - if we want to display it, it should be implemented in unchained and surfaced from it then displayed in both the Transactions section and Transactions History section and it would have to be a product decision, this PR just brings consistency.

## Notice

- [ ] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #1239

## Risk

N/A, the hiding is only done for receive Txs so we don't have risks of e.g send Txs miner fees being hidden, unless they are categorized as receive Txs which would be a bigger issue.

## Testing

- Go to Transactions History section on an account with receive Txs
- "Fees" table header should be displayed, but the actual row should be empty for it
- Clicking on it should also bring empty "Miner Fee" info

### CODE REVIEW

**Review by 0xdef1cafe — APPROVED** [review]

**Review by elmutt — APPROVED** [review]

File: src/components/TransactionHistoryRows/TransactionGenericRow.tsx [hunk 1]
```diff
@@ -157,29 +157,31 @@ export const TransactionGenericRow = ({
...
+                  />
+                  <Amount.Fiat
+                    color='gray.500'
+                    fontSize='sm'
+                    lineHeight='1'
+                    value={
+                      fee.amount
+                        ? bnOrZero(fromBaseUnit(fee.amount, fee.precision))
+                            .times(fee.currentPrice ?? 0)
+                            .toString()
```
Comment (cjthompson) [inline src/components/TransactionHistoryRows/TransactionGenericRow.tsx:178]:
```suggestion
                        ? bnOrZero(fromBaseUnit(fee.amount, fee.precision)
                            .times(fee.currentPrice))
                            .toString()
```
