### PR TITLE
fix: update balance charts

### LINKED ISSUE #691: data - balance charts remove accountType
now that we have the concept of individual accounts remove the accountType mess from useBalanceChartData

### PR DESCRIPTION
**Pull request by 0xdef1cafe**
## Description

fixes balance charts for everything except portfolio - eth, tokens, and btc asset and accounts all work correctly

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?
- [x] Do all new and existing tests pass? Does the linter pass?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #691

## Testing

1. go to bitcoin asset page and balance chart, right hand side of chart should end with full balance across all accounts
2. go to bitcoin account page and balance chart, right hand side of chart should end with balance for that account

## Screenshots (if applicable)

n/a

### CODE REVIEW

**Review by cjthompson — APPROVED** [review]

File: src/context/TransactionsProvider/TransactionsProvider.tsx [hunk 1]
```diff
@@ -47,6 +47,9 @@ export const TransactionsProvider = ({ children }: TransactionsProviderProps): J
                 const caip10 = `${msg.caip2}:${msg.address}`
                 const state = store.getState()
                 const accountId = selectAccountIdByAddress(state, caip10)
+                if (msg.txid.startsWith('8d')) {
+                  console.info(msg)
+                }
```
Comment (cjthompson) [inline src/context/TransactionsProvider/TransactionsProvider.tsx:52]: remove

**Review by kaladinlight — APPROVED** [review]
