### PR TITLE
fix: watchlist explore more assets escape hatch navigate out of memory router

### LINKED ISSUE #10571: Fix wallet router navigation
# Summary

We recently introduced a memory router wrapper around the wallet drawer to better handle inner routing. But the broken all the clicks that were routing out of the wallet drawer to different pages

# AC

We can click anything we want in the wallet drawer and it will correctly navigate

### PR DESCRIPTION
**Pull request by premiumjibles**
## Description

We recently introduced a memory router wrapper around the wallet drawer to better handle inner routing. But the broken all the clicks that were routing out of the wallet drawer to different pages. I've converted all those calls to use the browser router instead as an escape hatch. I've also ensured the drawer closes whenever we perform one of those navigations

## Issue (if applicable)

closes #10571 

## Risk

Low risk, fixes a number of bugs in the wallet drawer

> High Risk PRs Require 2 approvals

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

## Testing

* Make sure clicking the various buttons within the tabs in the wallet drawer correctly navigate to the correct pages
* Make sure any equivalent components (like my crypto on the mobile dashboard) still behave as expected

### Operations

- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)

https://jam.dev/c/2a933c5a-0689-4c76-a16a-55e58abddb33

## Summary by CodeRabbit

- New Features
  - Unified programmatic navigation across asset teasers, account/watchlist rows, staking views and empty-state CTAs; watchlist row taps include subtle haptic feedback.

- Bug Fixes
  - Wallet drawer reliably closes before navigation to prevent UI overlap.

- Refactor
  - Replaced router hook with a central navigation hook; some chain rows now only expand/collapse (no navigation).

- Chores
  - Public APIs simplified: removed external onRowClick and onExploreMore callbacks from account/watchlist components.

### CODE REVIEW

File: src/pages/Accounts/components/ChainRow.tsx [hunk 1]
```diff
@@ -67,15 +64,9 @@ export const ChainRow: React.FC<ChainRowProps> = ({ chainId, isSimpleMenu = fals
         chainId={chainId}
         isSimpleMenu={isSimpleMenu}
         onClose={onClose}
-        onClick={
-          // accountIds is strictly length 1 per accountNumber for account-based chains
-          !isUtxoAccountId(accountIds[0])
```
Comment (premiumjibles) [inline src/pages/Accounts/components/ChainRow.tsx:72]: We no longer show the account wallet page

File: src/components/StakingVaults/AssetTeaser.tsx
Comment (gomesalexandre) [inline src/components/StakingVaults/AssetTeaser.tsx:1]: Looks like we don't use this anymore? i.e we never pass `showTeaser` down.
That's a relic of having full-on DeFi opportunitie iirc - we can remove this guy altogether

**Comment by gomesalexandre** [comment]
Aligned Cosmos, RUNEPool, ETH/FOX staking with DeFi tab: https://jam.dev/c/45fd478f-fbb0-4a54-90e4-c29d568a2574 / e07ed14fd

**Review by gomesalexandre — CHANGES_REQUESTED** [review]
Actually noticed a regression in terms of "Manage" heuristics (both in existing DeFi tab, and in DeFi in new wallet popover, even though not live) which now navigate to asset page vs. opening the manage modal: https://jam.dev/c/d5162ef4-7bf4-459f-9972-7c3077eae82b

Doesn't seem expected, not sure if that's a regression or expected new behaviour but tmp requesting changes whilst I look at that 🙏🏽

File: src/components/EarnDashboard/components/PositionDetails/StakingPositionsByProvider.tsx [hunk 2]
```diff
@@ -6,7 +6,7 @@ import type { Asset, MarketData } from '@shapeshiftoss/types'
 import qs from 'qs'
 import { useCallback, useMemo } from 'react'
 import { useTranslate } from 'react-polyglot'
-import { useLocation, useNavigate } from 'react-router-dom'
+import { useLocation } from 'react-router-dom'
```
[the remark this answers is not in the document]
Comment (gomesalexandre) [reply src/components/EarnDashboard/components/PositionDetails/StakingPositionsByProvider.tsx:9]: meh

**Review by gomesalexandre — APPROVED** [review]
Fixed prod/develop DeFi tab regression in f0e2005818 / 335a3a4b4e 
: https://jam.dev/c/6f5c591a-ea21-4212-a8ec-0024e2368674

We may or may not bring manage click (now row click on new wallet drawer) behaviour back to new wallet drawer, but outside of the scope of smol changes here
