### PR TITLE
fix: update asset service and  market service api

### LINKED ISSUE #108: Update asset-service and market-service api

### PR DESCRIPTION
**Pull request by DaoDev44**
## Notice

Before submitting a pull request, please make sure you have answered the following:

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?
- [x] Do all new and existing tests pass? Does the linter pass?

## Pull Request Type

- [ ] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [x] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

If applicable, please link to the github issue and put `closes #XXXX` in your comment to auto-close the issue that your PR fixes.

closes #108 

## Description

Please describe your changes

This updates the breaking api changes from this [PR](https://github.com/shapeshift/lib/pull/50/files) and this [PR](https://github.com/shapeshift/lib/pull/49/files) to `getMarketData`, `byTokenId` and `getPriceHistory`

## Testing

Please outline all testing steps

1. Pull branch locally and run `yarn` to install new deps
2. etc...

### CODE REVIEW

File: src/components/Graph/Graph.tsx [hunk 1]
```diff
@@ -15,15 +15,20 @@ type GraphProps = {
 }
 
 export const Graph = ({ asset, timeframe, setPercentChange, isLoaded }: GraphProps) => {
-  const [data, setData] = useState<HistoryData[]>([])
+  const [data, setData] = useState<HistoryData[] | null>([])
```
Comment (TrancelikeTechno) [inline src/components/Graph/Graph.tsx:18]: when does this get set to `null`?

**Review by TrancelikeTechno — APPROVED** [review]

File: src/components/Graph/Graph.tsx (hunk 1 above)
Comment (technojak) [inline src/components/Graph/Graph.tsx:18]: when does this get set to null?

**Review by technojak — APPROVED** [review]

File: src/components/Graph/Graph.tsx (hunk 1 above)
Comment (0xdef1cafe) [reply src/components/Graph/Graph.tsx:18]: we changed the api of market service to return null on network failure rather than an empty array

it makes it easier to check than checking for array lengths

in reality no one will actually call `setData(null)` it's just to satisfy the compiler

**Review by 0xdef1cafe — APPROVED** [review]
