### PR TITLE
fix: add cosmos to feeAsset const

### LINKED ISSUE #1273: bug - cosmos display as both account and token
image

is this acceptable to fix in staking + delegation remaining work so we can ship cosmos base?

### PR DESCRIPTION
**Pull request by DaoDev44**
## Description

- Fix for cosmos showing up as an Account and a Token on the `Accounts` page.
-  The `Accounts` page relies on the selector `selectPortfolioAssetIdsByAccountIdExcludeFeeAsset` to exclude fee assets. All fee assets that are excluded need to be added to the constant array `FEE_ASSET_IDS` maually. This is definitely not ideal, and we should look at better ways to determine the fee assets of each chain dynamically so we don't have to manually add each fee asset as we implement more chains.

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #1273

## Risk
The risk associated with this fix is minimal, given the array is only used for this purpose.

## Testing

- Navigate to the `Accounts` page
- Cosmos should not have a token of the same name associated with it.

### CODE REVIEW

**Review by gomesalexandre — APPROVED** [review]

**Comment by gomesalexandre** [comment]
Confirmed this fixes ATOM showing as both an account and a token.
Unfortunately, I wasn't able to reproduce the wrong charts bug so I can't confirm whether or not this fixes it. Checking for the repro steps with @DaoDev44.

**Comment by gomesalexandre** [comment]
@DaoDev44 This will close https://github.com/shapeshift/web/issues/1273,  can you add `closes #1273` to the description 🙏🏽

**Review by 0xdef1cafe — APPROVED** [review]

File: src/state/slices/portfolioSlice/selectors.ts [hunk 1]
```diff
@@ -19,7 +19,11 @@ import {
 import { findAccountsByAssetId } from './utils'
 
 // We should prob change this once we add more chains
-const FEE_ASSET_IDS = ['eip155:1/slip44:60', 'bip122:000000000019d6689c085ae165831e93/slip44:0']
+const FEE_ASSET_IDS = [
+  'eip155:1/slip44:60',
+  'bip122:000000000019d6689c085ae165831e93/slip44:0',
+  'cosmos:cosmoshub-4/slip44:118'
+]
```
Comment (cjthompson) [inline src/state/slices/portfolioSlice/selectors.ts:26]:
```suggestion
  'cosmos:cosmoshub-4/slip44:118',
  'cosmos:osmosis-1/slip44:118''
]
```
