### PR TITLE
fix: fetch staking datas on message from websocket

### LINKED ISSUE #1409: Cosmos: need to refresh page after staking/unstaking
When staking/unstaking/claiming in Cosmos staking modal, account/staking/unstaking balance doesn't get properly updated.

#### Unstaking
- Open Cosmos Staking modal
- Go to Unstake 
- Unstake some amount of ATOM in a validator
- Undelegations do not get updated

#### Staking

- Open Cosmos Staking modal
- Go to Stake 
- Stake some amount of ATOM in a validator
- Staked amount in overview doesn't get updated
- Account Balance doesn't get updated

#### Rewards

- Open Cosmos Staking modal
- Go to Claim 
- Claim all your pending claims
- Account balance doesn't get updated
- Rewards don't get zero'd out

### A/C

- the `stakingDataSlice` redux state slice gets updated after a stake/unstake/claim Tx
  - the staked amount on a stake Tx gets added to the staking balance, deducted from the account balance (done in #1179)
  - the unstaked amount on an unstake Tx gets added to the unstaking balance / the undelegation entry gets populated / the value gets deducted from the staked amount
  - rewards amount is set to ~0 after a claim Tx
  
  
The account balance update shouldn't need to be updated on this issue as #1179 fixes it from the testing I've done.

### PR DESCRIPTION
**Pull request by NeOMakinG**
## Description
When you are claiming, staking or unstaking, every cosmos datas should be reloaded

## Notice

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)
closes #1409

## Risk
Not sure there are some risks, except if unchained is down when the reload happen!

## Testing
- Go on the cosmos staking modal, stake, claim or unstake and see if every datas are reloaded when the websocket send a message to the app

## Screenshots (if applicable)

https://user-images.githubusercontent.com/14963751/162471193-91c0244d-d909-4b6e-93fa-e045e6eec17f.mp4

### CODE REVIEW

File: src/context/TransactionsProvider/TransactionsProvider.tsx [hunk 1]
```diff
@@ -82,6 +83,14 @@ export const TransactionsProvider = ({ children }: TransactionsProviderProps): J
                     accountSpecifier: accountId
                   })
                 )
+                if (msg.chain === 'cosmos') {
```
Comment (gomesalexandre) [inline src/context/TransactionsProvider/TransactionsProvider.tsx:86]:
```suggestion
                if (msg.chain === ChainTypes.Cosmos) {
```

**Review by gomesalexandre — COMMENTED** [review]
One comment added as a CR comment rather than aggressively blocking the PR. Tested the same solution locally and works great!

**Review by gomesalexandre — APPROVED** [review]
🍬

**Review by theoboldfrazier — APPROVED** [review]

**Comment by 0xdef1cafe** [comment]
this may seem like the right place for this change, but this belong in the portfolio provider.

the transactions provider is concerned with providing transaction data to the app.

the portfolio provider is concerned with providing portfolio data to the app.

@NeOMakinG can you please merge/rebase off develop, have a look the changes i made recently, and insert this into the portfolio provider, where we refetch the portfolio on new transactions?

i also want to highlight that this stakingData slice needs to be removed entirely. it's a subset of account data. it comes from the endpoint call "getAccount". it belongs in the portfolio as a discriminated union under the cosmos account, and then my previous PR would have caught this.

**Review by 0xdef1cafe — CHANGES_REQUESTED** [review]
please see comments, wrong place for this

**Comment by NeOMakinG** [comment]
After a look at your changes, It seems that it would make no sense to use the `stakingDataSlice` inside the `PortfolioProvider` file, I would suggest doing the slice refactor, it will fix it naturally

**Comment by gomesalexandre** [comment]
> After a look at your changes, It seems that it would make no sense to use the `stakingDataSlice` inside the `PortfolioProvider`, I would suggest doing the slice refactor, it will fix it naturally

I can create a follow-up issue during the day, to remove the `stakingDataSlice` and move all of its logic inside `portfolioSlice`. It should be relatively straightforward, but very boilerplaty and prone to longer CR loops so **I would really vouch against doing so now** given the time constraints.
I'd rather go with:
- First shoehorn that refresh call into `PortfolioProvider`
- Then as a follow-up, move the `stakingDataSlice` into `portfolioSlice`

This way, you can both have your cake now (release) and eat it next week (clean slice).

**Comment by NeOMakinG** [comment]
Tested with @0xdef1cafe changes, it's updated as needed, so we don't need this PR anymore, but we should create an issue regarding the slice refactor!

File: src/context/PortfolioProvider/PortfolioContext.tsx [hunk 2]
```diff
@@ -206,6 +207,24 @@ export const PortfolioProvider = ({ children }: { children: React.ReactNode }) =
     [accountSpecifiersList, dispatch],
   )
 
+  /**
+   * refetch an account given a newly confirmed txid
+   */
+  const refetchStakingDataByTxId = useCallback(
+    (txId: TxId) => {
+      // the accountSpecifier the tx came from
+      const { txAccountSpecifier } = deserializeUniqueTxId(txId)
```
Comment (gomesalexandre) [inline src/context/PortfolioProvider/PortfolioContext.tsx:216]: `txId` should always be defined/a string with length and thus we don't technically need it, but I'd add it just for that bit of extra safety and to lead by example in case someone's looking in this implementation and want to dispatch `stakingDataApi.endpoints.getStakingData.initiate` somewhere else in the codebase, where `accountSpecifier` might be an empty string.

```suggestion
      const { txAccountSpecifier } = deserializeUniqueTxId(txId)
      if (txAccountSpecifier.length) return
```

**Review by gomesalexandre — APPROVED** [review]

**Review by gomesalexandre — APPROVED** [review]

**Comment by 0xdef1cafe** [comment]
> > After a look at your changes, It seems that it would make no sense to use the `stakingDataSlice` inside the `PortfolioProvider`, I would suggest doing the slice refactor, it will fix it naturally
> 
> I can create a follow-up issue during the day, to remove the `stakingDataSlice` and move all of its logic inside `portfolioSlice`. It should be relatively straightforward, but very boilerplaty and prone to longer CR loops so **I would really vouch against doing so now** given the time constraints. I'd rather go with:
> 
> * First shoehorn that refresh call into `PortfolioProvider`
> * Then as a follow-up, move the `stakingDataSlice` into `portfolioSlice`
> 
> This way, you can both have your cake now (release) and eat it next week (clean slice).

ya, this is the wei

**Review by elmutt — APPROVED** [review]

**Review by 0xdef1cafe — APPROVED** [review]

**Comment by 0xdef1cafe** [comment]
cool, much nicer, and we can remove this in one spot when we remove the stakingData slice
