### PR TITLE
fix: add fox benefits rfox asset selectors

### LINKED ISSUE #8510: Add asset selector for FOX Benefits to toggle FOX vs LP
https://www.figma.com/design/lqcttmmnGtRtbjb8evL6Le/FOX-page?node-id=814-675&t=EE8bwloE1yRE1yaC-0 (figma currently not loading, but this should be the correct link) 

- Add the selector for assets to the Fox Bene page
- toggle data based on the selection

### PR DESCRIPTION
**Pull request by NeOMakinG**
## Description

Added the Asset selector to the RFOX section of the fox benefits page

Fixed a bug in `useLifetimeRewardsQuery` where the select was throwing an error because `detailsByStakingContract` for the lp contract is not existing yet

Passed stakingAssetId everywhere to get the right data for the right contract

## Issue (if applicable)

closes #8510

## Risk

> High Risk PRs Require 2 approvals

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

## Testing
- Go to the FOX Benefits page
- Try to select the LP asset for the RFOX section
- See all informations should be calculated again

### Operations

- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)
image

### CODE REVIEW

File: src/pages/Fox/components/RFOXSection.tsx [hunk 1]
```diff
@@ -236,20 +242,34 @@ export const RFOXSection = () => {
             <Heading as='h2' fontSize='2xl' display='flex' alignItems='center'>
               <RFOXIcon me={2} boxSize='32px' sx={rfoxIconStyles} />
               {translate('RFOX.staking')}
-              <Skeleton isLoaded={!Boolean(isApyLoading)} ml={2}>
+              <Skeleton isLoaded={!currentApyQuery.isFetching} ml={2}>
```
Comment (gomesalexandre) [inline src/pages/Fox/components/RFOXSection.tsx:245]: 💜

File: src/pages/Fox/components/RFOXSliders.tsx [hunk 2]
```diff
@@ -74,7 +80,7 @@ export const RFOXSliders: React.FC<RFOXSlidersProps> = ({
               customInput={Input}
               isNumericString={true}
               inputMode='decimal'
-              suffix={' FOX'}
+              suffix={` ${stakingAsset?.symbol ?? ''}`}
```
Comment (gomesalexandre) [inline src/pages/Fox/components/RFOXSliders.tsx:83]: nitpick:
```suggestion
              suffix={stakingAsset?.symbol}
```

**Review by gomesalexandre — COMMENTED** [review]
Diff looking sane - runtime pass incoming!

**Review by gomesalexandre — APPROVED** [review]
Tested locally, confirmed this does what it says on the box! Great one ser 🐐 

https://jam.dev/c/42d6974f-09b4-403c-b477-249ba15bcd06

One thing I've spotted which isn't inherently blocking but would be nice-to-have is account number is carried over when clicking "Manage", but staking asset isn't. Not sure how much of a lift that is, so stamping regardless.
