### PR TITLE
fix: wallet popover weirdness when connected to ledger

### LINKED ISSUE #10475: Fix mobile wallet popover not opening properly when ledger connected
Seems to just open the manage accounts modal for some reason

### PR DESCRIPTION
**Pull request by premiumjibles**
## Description

Currently when you connect to a ledger and try to open the wallet popover, it will keep spamming you with the manage accounts modal. Most likely something is triggering the ledger menu to to rerender and retrigger the useEffect that's in there to open the modal.

I've lifted that logic up to a more global position and tried to make it a bit less trigger happy.

## Issue (if applicable)

closes #10475 

## Risk

Low risk, should only effect the account management auto popup for newly connected ledgers.

> High Risk PRs Require 2 approvals

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

## Testing
* Open app in incognito
* Connect a new ledger
* Verify that it forces you to select accounts if you haven't got any already
* Pick some accounts
* Verify it no longer prompts you
* Verify you can open the mobile wallet popover

### Operations

- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)

https://jam.dev/c/c308c1c0-b460-448a-bfa8-e3807520d362

## Summary by CodeRabbit

* **New Features**
  * Smarter Ledger onboarding: when connecting a Ledger with no accounts, the Manage Accounts modal opens automatically. No change for other cases.

* **Bug Fixes**
  * Wallet popover now closes automatically when the wallet disconnects, preventing stale UI.

* **Refactor**
  * Streamlined Ledger connection behavior to avoid unnecessary automatic modal openings and provide a more predictable experience.

### CODE REVIEW

File: src/components/Layout/Header/NavBar/PopoverWallet.tsx [hunk 1]
```diff
@@ -89,6 +89,13 @@ export const PopoverWallet: FC<PopoverWalletProps> = memo(({ onClose }) => {
     dispatch({ type: WalletActions.SET_WALLET_MODAL, payload: true })
   }, [dispatch])
 
+  // Auto-close popover when wallet is disconnected
```
Comment (premiumjibles) [inline src/components/Layout/Header/NavBar/PopoverWallet.tsx:92]: This was a drive by fix. Wallet popover needs to close when you disconnect

File: src/context/WalletProvider/Ledger/components/LedgerMenu.tsx [hunk 2]
```diff
@@ -1,46 +1,23 @@
...
+  const { dispatch } = useWallet()
   const translate = useTranslate()
   const isAccountManagementEnabled = useFeatureFlag('AccountManagement')
   const isLedgerAccountManagementEnabled = useFeatureFlag('AccountManagementLedger')
-  const accountManagementPopover = useModal('manageAccounts')
-
-  const [hasCompletedChainInit, setHasCompletedChainInit] = useState(false)
-
-  // We want this to run just once, upon Ledger connection, to show the user their connected chains and accounts
-  useEffect(() => {
```
Comment (premiumjibles) [inline src/context/WalletProvider/Ledger/components/LedgerMenu.tsx:27]: This is the useEffect that keeps triggering when you open the wallet popover model

File: src/hooks/useLedgerAccountCheck/useLedgerAccountCheck.tsx [hunk 3]
```diff
@@ -0,0 +1,37 @@
+import { useEffect, useRef } from 'react'
+import { useSelector } from 'react-redux'
+
+import { useModal } from '@/hooks/useModal/useModal'
+import { useWallet } from '@/hooks/useWallet/useWallet'
+import { selectIsPortfolioLoading, selectPortfolioAccounts } from '@/state/slices/selectors'
+
+export const useLedgerAccountCheck = () => {
```
Comment (NeOMakinG) [inline src/hooks/useLedgerAccountCheck/useLedgerAccountCheck.tsx]: I don't know about the name, maybe `useLedgerAccountGuard` or something that feels like this hook could block the app usage

File: src/components/Layout/Header/NavBar/PopoverWallet.tsx (hunk 1 above)
Comment (NeOMakinG) [reply src/components/Layout/Header/NavBar/PopoverWallet.tsx:92]: Makes sense

**Comment by premiumjibles** [comment]
Renamed to useLedgerAccountGuard @NeOMakinG
