### PR TITLE
fix: load a zero balance chart when using a wallet with zero balances

### LINKED ISSUE #815: [ALPHA]  No dashboard load with fresh wallet
https://discord.com/channels/554694662431178782/873244924026449940/933122161856634900

Description: When creating a new wallet/using a wallet with zero balances or trade history, the main dashboard and asset balance dashboards never load a zero balance chart

Recreation steps
1. go to app.shapeshift.com
2. go through create a new wallet flow
3. log in to the said new wallet
4. observe charts not loading on dashboard

Native test wallet no balancetransaction history

### PR DESCRIPTION
**Pull request by jdambron**
## Description

Load a zero balance chart when using a wallet with zero balances or trade history

## Notice

Before submitting a pull request, please make sure you have answered the following:

- [x] Have you followed the guidelines in our [Contributing]('https://github.com/shapeshift/web/CONTRIBUTING.md) guide?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/shapeshift/web/pulls) for the same update/change?
- [x] Do all new and existing tests pass? Does the linter pass?

## Pull Request Type

- [x] :bug: Bug fix (Non-breaking Change: Fixes an issue)
- [ ] :hammer_and_wrench: Chore (Non-breaking Change: Doc updates, pkg upgrades, typos, etc..)
- [ ] :nail_care: New Feature (Breaking/Non-breaking Change)

## Issue (if applicable)

closes #815

## Testing

1. Create a new fresh native wallet
2. The dashboard should display a flat line with 0 balance

### CODE REVIEW

File: src/hooks/useBalanceChartData/useBalanceChartData.ts [hunk 1]
```diff
@@ -333,10 +332,8 @@ export const useBalanceChartData: UseBalanceChartData = args => {
     // data prep
     const noDeviceId = isNil(walletInfo?.deviceId)
     const noAssetIds = !assetIds.length
-    const noTxs = !txs.length
-    const noBalances = isEmpty(balances)
     const noPriceHistory = priceHistoryDataLoading
-    if (noDeviceId || noAssetIds || noTxs || noBalances || noPriceHistory) {
```
Comment (daodev877) [inline src/hooks/useBalanceChartData/useBalanceChartData.ts:339]: hi @jdambron,
what was the issue exactly? 

I might be wrong but It seems like this change introduces a new issue:
checks for `txs` & `balances` make sense as these values passed to `bucketTxs ` and `makeBuckets` later

https://github.com/shapeshift/web/blob/755853c36c3a107320a2891411e28fb85393cf66/src/hooks/useBalanceChartData/useBalanceChartData.ts#L105
`makeBuckets` will throw an error if `balances` is empty

---

it would be great to add a couple of tests for `useBalanceChartData`

Comment (jdambron) [reply src/hooks/useBalanceChartData/useBalanceChartData.ts:339]: Hi @daodev877.
From my understanding, the issue was that we return `setBalanceChartDataLoading(true)` in this case, meaning that we stay in a loading state endlessly if we have no balances / no transactions.
I may be wrong.

Comment (0xdef1cafe) [reply src/hooks/useBalanceChartData/useBalanceChartData.ts:339]: Hey guys

You're both pretty close here

The way I would address this is pull in the portfolio loaded selector that checks if we have accounts, and also if txs has finished loading. 

This is kind of tricky as we can't *really* tell when txs have finished loading, we just debounce the web socket.

I probably wouldn't remove the balanced or txs check completely as then the chart will probably furiously render as each tx comes in. 

I'll take a look locally when I'm at a computer that this doesn't impact perf badly with an account with lots of txs.

Comment (0xdef1cafe) [reply src/hooks/useBalanceChartData/useBalanceChartData.ts:339]: ok, i pulled this locally and had a play, it actually performs fine - no crazy renders and works for both empty wallets and wallets with significant tx history. 

it seems the debounce is enough to stop the furious rendering, and @daodev877 the `isEmpty(balances)` check seemed redundant, and this works as expected.

a lot of those guard conditions were left over from before we did a big state refactor, it's possible more could go away, but for now this is great.

**Review by 0xdef1cafe — APPROVED** [review]

**Review by DaoDev44 — APPROVED** [review]

**Comment by jdambron** [comment]
Thank you @0xdef1cafe :pray:
