### PR TITLE
fix: address book baby

### LINKED ISSUE #10694: Redesign The Send Flow on desktop
Desktop version of the already-implemented (by the time this ticket starts) send flow.  

This will appear in the current version of the send modal. <br><br>Some key differences between this and mobile. 

1. The amount, and send to address are inside one component. 
2. Tapping on the address fields shows an autocomplete address popover.
   1. Once a user starts typing in the field, we will filter the list. 
   2. If none match the string they have searched we should show an empty state.
3. The user can change accounts by tapping the account selector at the footer of the modal. This will trigger a popover with their accounts showing the current account selected.
4. If a user has manually types or pasted in a new address, we should show a "Save" button to the right of the address field. 
   1. Tapping save triggers the save contact modal.
   2. Once a contact is saved, the manual address should be replaced by the contact version of the value.

Figma Prototype

[Amount - With Contact - Send Flow (Figma)](https://www.figma.com/proto/O80UA9NWHSpsa1tbFfnbum/Send-Flow?node-id=2717-6097&p=f&t=pvgv7Msk08uNxfnU-0&scaling=min-zoom&content-scaling=fixed&page-id=2717%3A5317&starting-point-node-id=2717%3A6097)

Screens

[Desktop Flow - Send Flow (Figma)](https://www.figma.com/design/O80UA9NWHSpsa1tbFfnbum/Send-Flow?node-id=2717-5318&t=pvgv7Msk08uNxfnU-0)

### PR DESCRIPTION
**Pull request by NeOMakinG**
## Description

This PR adds the address book into the send flow:
- A way to add an address to it
- A way to delete addresses (by having a confirm modal)
- Be able to select and search an address from the address book
- Add migrations for the address book
- A flag to disable it for now in production but enable on develop
- Bring back ens resolving at address step, show them in every other steps
- Internal account resolutions for any accounts that are not UTXOs

## Issue (if applicable)

closes #10694

## Risk
Low, new feature behind a flag
> High Risk PRs Require 2 approvals

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

## Testing
- Go in the send flow
- Add an address to the input, notice the "save" button
- Click save, add an address to your address book
- Add multiple addresses
- Try to search by typing in the input, by name or address
- Notice if the address in the input is matching we are showing every addresses from the address book
- If the address is full and valid, the address book is showing all addresses
- Notice the address book show addresses only for the current namespace, so if you are sending some UTXOs we are not showing EVM addresses
- Clicking on the selected address book component is showing the input so you can change the address
- Input is autofocusing on click
- You can delete an address by clicking the trash icon and confirming
- Try to input an ENS address
- Try to input an internal address (account you have activated in the current wallet)
- Both mobile and desktop works the same

### Operations

- [x] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)
image
image
image
image
image
image
image
image
image
image

## Summary by CodeRabbit

* **New Features**
  * Address book: save, search, select, and delete addresses with confirmation and a save modal; persisted storage and migrations; feature flag to toggle.

* **UI**
  * New translations and labels (Save, Delete, address book strings).
  * Avatars and improved recipient display in confirmation screens.
  * Unified address input and QR-scan interactions for a consistent send experience.

* **Chores**
  * Simplified send flow navigation for consistent behavior across viewports.

### CODE REVIEW

File: src/state/slices/addressBookSlice/addressBookSlice.ts [hunk 1]
```diff
@@ -0,0 +1,57 @@
...
+import { createSlice } from '@reduxjs/toolkit'
+import type { ChainId } from '@shapeshiftoss/caip'
+
+export type AddressBookEntry = {
+  id: string
+  name: string
+  address: string
+  chainId: ChainId
+  createdAt: number
+}
```
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: Fixed in 58ff44f90d - Consolidated AddressBookEntry type to single source of truth. Removed duplicate type definition in AddressBook.tsx and imported from addressBookSlice.ts.

File: src/state/slices/addressBookSlice/addressBookSlice.ts [hunk 2]
```diff
@@ -0,0 +1,57 @@
...
+        const id = `${action.payload.chainId}_${action.payload.address}_${Date.now()}`
+        const entry: AddressBookEntry = {
+          ...action.payload,
+          id,
+          createdAt: Date.now(),
+        }
+        state.byId[id] = entry
+        state.ids.push(id)
+      },
+    ),
```
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: Fixed in 58ff44f90d - Fixed Date.now() being called twice by using single `const now` variable, and added duplicate address validation to prevent saving the same address multiple times.

File: src/components/Modals/Send/views/SendAmountDetails.tsx [hunk 3]
```diff
@@ -259,6 +237,17 @@ export const SendAmountDetails = () => {
...
+  const handleSaveContact = useCallback(
+    (e: React.MouseEvent<HTMLButtonElement>) => {
+      e.stopPropagation()
+
+      if (to && asset?.chainId) {
+        addAddress.open({ address: to, chainId: asset.chainId })
+      }
+    },
+    [to, asset?.chainId, addAddress],
+  )
```
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply src/components/Modals/Send/views/SendAmountDetails.tsx]: Fixed in 58ff44f90d - Added feature flag check to gate the save contact functionality.

File: src/components/Modals/Send/views/SendAmountDetails.tsx [hunk 4]
```diff
@@ -317,12 +306,7 @@ export const SendAmountDetails = () => {
   return (
     <SlideTransition className='flex flex-col h-full'>
       <DialogHeader>
-        <Display.Mobile>
-          <DialogBackButton onClick={handleBackClick} />
-        </Display.Mobile>
-        <Display.Desktop>
-          <DialogBackButton onClick={handleAssetBackClick} />
-        </Display.Desktop>
+        <DialogBackButton onClick={handleBackClick} />
```
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply src/components/Modals/Send/views/SendAmountDetails.tsx]: Fixed in 58ff44f90d - Added aria-label for screen reader accessibility.

File: .env.development [hunk 5]
```diff
@@ -6,6 +6,7 @@
 
 # feature flags
 VITE_FEATURE_THORCHAIN_TCY_ACTIVITY=true
+VITE_FEATURE_ADDRESS_BOOK=true
```
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply .env.development:9]: No action needed - We don't have a linter enforcing dotenv ordering, and this is a very minor stylistic concern.

File: src/components/Modals/Send/AddressBook/AddressBook.tsx [hunk 6]
```diff
@@ -0,0 +1,226 @@
...
+  id: string
+  name: string
+  address: string
+}
+
+type AddressBookEntryButtonProps = {
+  entry: AddressBookEntry
+  onSelect: (address: string) => void
+  onDelete: (id: string) => void
+}
```
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply src/components/Modals/Send/AddressBook/AddressBook.tsx]: No action needed - This is a factory pattern. handleDeleteConfirm returns a no-arg callback that captures the entry ID in its closure. The types are correct and it works as intended.

File: src/components/Modals/Send/AddressBook/AddressBook.tsx [hunk 7]
```diff
@@ -0,0 +1,226 @@
...
+    formState: { errors },
+  } = useFormContext()
+  const { isOpen, onClose, onOpen } = useDisclosure({
+    defaultIsOpen: false,
+  })
+  const [selectedDeleteEntry, setSelectedDeleteEntry] = useState<AddressBookEntry | null>(null)
+  const addressBookEntries = useAppSelector(state =>
+    selectAddressBookEntriesByChainNamespace(state, chainId ?? ''),
+  )
+
```
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply src/components/Modals/Send/AddressBook/AddressBook.tsx]: Fixed in 58ff44f90d - Added defensive guard in the selector itself to return empty array when chainId is falsy, preventing fromChainId('') crash.

File: src/components/Modals/Send/views/Address.tsx [hunk 8]
```diff
@@ -150,6 +169,31 @@ export const Address = () => {
     navigate(SendRoutes.Scan)
   }, [navigate])
 
+  const handleSelectAddressBookEntry = useCallback(
+    (entryAddress: string) => {
+      setValue(SendFormFields.Input, entryAddress, { shouldValidate: true })
+      navigate(SendRoutes.AmountDetails)
+    },
+    [setValue, navigate],
+  )
```
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply src/components/Modals/Send/views/Address.tsx]: No action needed - The validation race doesn't occur in practice. The shouldValidate flag ensures validation runs, and the navigation timing works correctly in the app.

File: src/state/slices/addressBookSlice/selectors.ts [hunk 9]
```diff
@@ -0,0 +1,62 @@
...
+        { key: 'address', threshold: matchSorter.rankings.CONTAINS },
+      ],
+    })
+
+    return matchedEntries
+  },
+)(
+  (_state: ReduxState, filter: SearchQueryFilter) =>
+    `${filter.chainId}_${filter.searchQuery ?? 'addressBookEntriesBySearchQuery'}`,
+)
```
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/selectors.ts]: No action needed - This is premature optimization. The current implementation works fine for our use case. If we observe performance issues in production, we can revisit this with LRU caching.

File: .env.production [hunk 10]
```diff
@@ -1,6 +1,7 @@
 # feature flags
 VITE_FEATURE_MIXPANEL=true
 VITE_ENABLE_ADDRESSABLE=true
+VITE_FEATURE_ADDRESS_BOOK=false
```
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply .env.production:4]: No action needed - We don't have a linter enforcing dotenv ordering, and this is a very minor stylistic concern.

File: src/components/Modals/Send/AddAddressModal.tsx [hunk 11]
```diff
@@ -0,0 +1,134 @@
...
+            <FormControl isInvalid={!!errors.name}>
+              <Input
+                {...register('name', {
+                  required: translate('modals.send.addContact.nameRequired'),
+                  minLength: {
+                    value: 1,
+                    message: translate('modals.send.addContact.nameRequired'),
+                  },
+                })}
+                placeholder={translate('modals.send.addContact.namePlaceholder')}
```
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply src/components/Modals/Send/AddAddressModal.tsx]: No action needed - If a user wants to save a whitespace-only name, that's their choice. This validation is too nitpicky for the user experience.

File: src/components/Modals/Send/views/Address.tsx [hunk 12]
```diff
@@ -77,10 +83,23 @@ export const Address = () => {
   )
 
   const asset = useAppSelector(state => selectAssetById(state, assetId))
+  const addressBookEntries = useAppSelector(state =>
+    selectAddressBookEntriesByChainNamespace(state, asset?.chainId ?? ''),
+  )
```
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply src/components/Modals/Send/views/Address.tsx]: Fixed in 58ff44f90d - Added defensive guard in the selector itself to return empty array when chainId is falsy, preventing fromChainId('') crash.

File: src/components/Modals/Send/views/Confirm.tsx [hunk 13]
```diff
@@ -111,6 +113,14 @@ export const Confirm = ({ handleSubmit }: ConfirmProps) => {
     state: { wallet },
   } = useWallet()
 
+  const addressBookEntries = useAppSelector(state =>
+    selectAddressBookEntriesByChainNamespace(state, asset?.chainId ?? ''),
+  )
+
```
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply src/components/Modals/Send/views/Confirm.tsx]: Fixed in 58ff44f90d - Added defensive guard in the selector itself to return empty array when chainId is falsy, preventing fromChainId('') crash.

File: src/state/slices/addressBookSlice/addressBookSlice.ts [hunk 14]
```diff
@@ -0,0 +1,62 @@
+import type { PayloadAction } from '@reduxjs/toolkit'
+import { createSlice } from '@reduxjs/toolkit'
+import type { ChainId } from '@shapeshiftoss/caip'
+
+export type AddressBookEntry = {
+  id: string
+  name: string
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/addressBookSlice.ts]: gnomes nitpick: prefer `label` in this particular scenario

File: src/state/slices/addressBookSlice/addressBookSlice.ts [hunk 15]
```diff
@@ -0,0 +1,62 @@
+import type { PayloadAction } from '@reduxjs/toolkit'
+import { createSlice } from '@reduxjs/toolkit'
+import type { ChainId } from '@shapeshiftoss/caip'
+
+export type AddressBookEntry = {
+  id: string
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/addressBookSlice.ts]: q: I get the "we use the store as a poor man's db" but isn't that fluff in this particular case?

File: src/state/slices/addressBookSlice/addressBookSlice.ts [hunk 16]
```diff
@@ -0,0 +1,62 @@
...
+  name: string
+  address: string
+  chainId: ChainId
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/addressBookSlice.ts]: q: should we be overly abstracting this and think of adding an optional `accountId` here?
i.e for account-based chains, `Address` + `ChainId` = `AccountId`.

But say we're going to support address book for sending over your own accounts (which IMO is one of the main benefits of this), then, a given account (i.e a certain BIP32 path, like `m/44’/0’/0’/0/0`) has an infinity of addies potentially so this wouldn't really make sense for these.

IMO, doesn't hurt to be overly thinking of this scenario as it's not a stretch, but one of the main (if not *the*) use cases: should probably be a discriminated union of `address` + `chainId` *or* `AccountId` - WDYT?

File: src/state/slices/addressBookSlice/addressBookSlice.ts [hunk 17]
```diff
@@ -0,0 +1,62 @@
...
+  createdAt: number
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/addressBookSlice.ts]: q: I get the copypastaroo here but do we need to know when an address was added? Feels fluff.

File: src/state/slices/addressBookSlice/addressBookSlice.ts [hunk 18]
```diff
@@ -0,0 +1,62 @@
...
+          const existing = state.byId[existingId]
+          return (
+            existing.chainId === action.payload.chainId &&
+            existing.address === action.payload.address
+          )
+        })
+        if (isDuplicate) return
+
+        const now = Date.now()
+        const id = `${action.payload.chainId}_${action.payload.address}_${now}`
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/addressBookSlice.ts]: q: is the intent to have a shared address book *across* wallets? Assuming yes, but verifying here.

File: src/state/slices/addressBookSlice/addressBookSlice.ts (hunk 16 above)
Comment (gomesalexandre) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: With that said - while `chainId` does sound sane, I'm seeing one bigly issue with this. The way e.g Rabby handles this is EVM addresses are shared across all EVM chains, that's in comparison with MM holding different address book registries across EVM chains, which is infuriating as a user.

If we're going with this, we wouldn't really be able to handle that. 

While I think storing the `ChainId` (and/or a full `AccountId`) is sane - we should ensure we dedupe (i.e same pubkey, diff `ChainId`) over EVM chains so that a given address book entry is detected over all EVM chains.

As a user, this means sending to a given EVM addy, adding to address book, then sending again but on a diff chain shouldn't be detected as able to add new entry. Looking at the current serialisation, doesn't look like that would work?

File: src/state/slices/addressBookSlice/addressBookSlice.ts [hunk 19]
```diff
@@ -0,0 +1,62 @@
...
+  name: 'addressBook',
+  initialState,
+  reducers: create => ({
+    addAddress: create.reducer(
+      (state, action: PayloadAction<Omit<AddressBookEntry, 'id' | 'createdAt'>>) => {
+        // Extra safety just in case logic is broken on UI side and the user adds the same address twice
+        const isDuplicate = state.ids.some(existingId => {
+          const existing = state.byId[existingId]
+          return (
+            existing.chainId === action.payload.chainId &&
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/addressBookSlice.ts]: That wouldn't dedupe over EVM chains right?

File: src/state/slices/addressBookSlice/addressBookSlice.ts (hunk 18 above)
Comment (gomesalexandre) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: Also - this serialisation feels off? i.e why do we need to serialise with a timestamp?

File: src/state/slices/addressBookSlice/addressBookSlice.ts [hunk 20]
```diff
@@ -0,0 +1,62 @@
...
+export type AddressBookEntry = {
+  id: string
+  name: string
+  address: string
+  chainId: ChainId
+  createdAt: number
+}
+
+export type AddressBookState = {
+  byId: Record<string, AddressBookEntry>
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/addressBookSlice.ts]: q: can we either/or:

1. have a flavoured string of sorts for K
2. make this `byPubKey` (or whatever K is) to keep things declarative and readable without needing to dig in the implementation

File: src/state/slices/addressBookSlice/addressBookSlice.ts [hunk 21]
```diff
@@ -0,0 +1,62 @@
...
+      },
+    ),
+    deleteAddress: create.reducer((state, action: PayloadAction<string>) => {
+      delete state.byId[action.payload]
+      state.ids = state.ids.filter(id => id !== action.payload)
+    }),
+    clear: create.reducer(() => initialState),
+  }),
+  selectors: {
+    selectAddressBookEntries: state => state.ids.map(id => state.byId[id]),
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/addressBookSlice.ts]: recommendation: to keep things declarative and readable (I am gnomes reading this without third coffee yet, which is a good Litmus test of approachability here) could use `Address` vernacular across the board or something like that.
Two hard things in SW ikik, but just feels like `Entries` may be too lower level and not convey enough?

Or perhaps I'm overthinking this and you can reply "gnomes silence pls robot"

File: src/state/slices/addressBookSlice/addressBookSlice.ts [hunk 22]
```diff
@@ -0,0 +1,62 @@
...
+    selectAddressBookEntryById: (state, entryId: string) => state.byId[entryId],
+    selectAddressBookEntriesByChainId: (state, chainId: ChainId) =>
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/addressBookSlice.ts]: ditto EVM chains, who's a very naughty boi? That's a very naughty boi right here

File: src/state/slices/addressBookSlice/addressBookSlice.ts [hunk 23]
```diff
@@ -0,0 +1,62 @@
...
+export const initialState: AddressBookState = {
+  byId: {},
+  ids: [],
+}
+
+export const addressBookSlice = createSlice({
+  name: 'addressBook',
+  initialState,
+  reducers: create => ({
+    addAddress: create.reducer(
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/addressBookSlice.ts]: i.e this guy *does* use address vernacular which is noice, perhaps we want to use that across the board?

File: src/state/slices/addressBookSlice/addressBookSlice.ts [hunk 24]
```diff
@@ -0,0 +1,62 @@
...
+      (state, action: PayloadAction<Omit<AddressBookEntry, 'id' | 'createdAt'>>) => {
+        // Extra safety just in case logic is broken on UI side and the user adds the same address twice
+        const isDuplicate = state.ids.some(existingId => {
+          const existing = state.byId[existingId]
+          return (
+            existing.chainId === action.payload.chainId &&
+            existing.address === action.payload.address
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/addressBookSlice.ts]: One comment re: this guy across all actions: 

Do we want to normalize addies? i.e use `getAddress()` for EVM addies, and counterpart for pubkeys (xpub/address) on other chains, so that we use the same checksum?

Or perhaps just go all lowercase. Or perhaps do nothing. Whichever one we go with, ideally we should ensure that:

- We can do lookups by addresses without missed hits because of non/checksummed
- We do consistent checks across the board re non/checksummed when referencing addies

File: src/state/slices/addressBookSlice/selectors.ts [hunk 25]
```diff
@@ -0,0 +1,65 @@
...
+import { addressBookSlice } from './addressBookSlice'
+
+import type { ReduxState } from '@/state/reducer'
+
+export const selectAddressBookEntries = createSelector(
+  addressBookSlice.selectors.selectAddressBookEntries,
+  entries => entries,
+)
+
+export const selectAddressBookEntriesByChainNamespace = createCachedSelector(
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/selectors.ts]: 👀

File: src/state/slices/addressBookSlice/selectors.ts [hunk 26]
```diff
@@ -0,0 +1,65 @@
...
+  addressBookSlice.selectors.selectAddressBookEntries,
+  (_state: ReduxState, chainId: ChainId) => chainId,
+  (entries, chainId) => {
+    if (!chainId) return []
+
+    const { chainNamespace } = fromChainId(chainId)
+
+    // Filter entries that match the same chain namespace
+    // This allows addresses to work across all chains of the same type
+    // (e.g., an Ethereum address works on all EVM chains)
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/selectors.ts]: Doesn't generalise to UTXOs however:

```typescript
export const CHAIN_NAMESPACE = {
  Evm: 'eip155',
  Utxo: 'bip122',
  CosmosSdk: 'cosmos',
  Solana: 'solana',
} as const
```

i.e with this logic, a THOR address would be valid for Maya and CosmosHub, a DOGE addy would be valid for BTC etc.

File: src/state/slices/addressBookSlice/selectors.ts [hunk 27]
```diff
@@ -0,0 +1,65 @@
...
+  return chainNamespace
+})
+
+type SearchQueryFilter = {
+  chainId: ChainId
+  searchQuery: string
+}
+
+const selectSearchQueryFromFilter = (_state: ReduxState, filter: SearchQueryFilter) =>
+  filter.searchQuery
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/selectors.ts]: Parametrised filters should live next to thy others

File: src/state/slices/addressBookSlice/selectors.ts [hunk 28]
```diff
@@ -0,0 +1,65 @@
...
+
+export const selectAddressBookEntriesBySearchQuery = createCachedSelector(
+  (state: ReduxState, filter: SearchQueryFilter) =>
+    selectAddressBookEntriesByChainNamespace(state, filter.chainId),
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/selectors.ts]: syntax looks off - i.e see comment above re: use conventional `selectXyzParamFromFilter`

File: src/state/slices/addressBookSlice/selectors.ts (hunk 26 above)
Comment (gomesalexandre) [reply src/state/slices/addressBookSlice/selectors.ts]: I mean does feel we may want to keep this guy... but rename and use it for EVM chains only?

File: src/state/slices/addressBookSlice/selectors.ts [hunk 29]
```diff
@@ -0,0 +1,65 @@
...
+  selectSearchQueryFromFilter,
+  (entries, searchQuery) => {
+    if (!searchQuery) return entries
+
+    const matchedEntries = matchSorter(entries, searchQuery, {
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/selectors.ts:49]: I mean why not eyy

File: src/state/slices/addressBookSlice/selectors.ts [hunk 30]
```diff
@@ -0,0 +1,65 @@
...
+      keys: [
+        { key: 'name', threshold: matchSorter.rankings.MATCHES },
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/selectors.ts]: q: wondering if we want to block ability from adding same label over two addies for paranoia purposes or am I gnoming too much?

File: src/context/ModalProvider/ModalContainer.tsx [hunk 31]
```diff
@@ -221,6 +221,14 @@ const WalletDrawer = makeSuspenseful(
   ),
 )
 
+const AddAddressModal = makeSuspenseful(
+  lazy(() =>
+    import('@/components/Modals/Send/AddAddressModal').then(({ AddAddressModal }) => ({
```
Comment (gomesalexandre) [inline src/context/ModalProvider/ModalContainer.tsx]: suggestion: should probably use the address book vernacular here - intent not super clear from component/module name.
Perhaps even "save" terminology?

File: src/components/Modals/Send/SendCommon.tsx [hunk 32]
```diff
@@ -5,9 +5,10 @@ export enum SendRoutes {
   Scan = '/send/scan',
   Select = '/send/select',
   Address = '/send/address',
+  Amount = '/send/amount',
 }
 
-export const mobileSendRoutes = [
+export const sendRoutes = [
```
Comment (gomesalexandre) [inline src/components/Modals/Send/SendCommon.tsx]: 👀

File: src/components/Modals/Send/Send.tsx [hunk 33]
```diff
@@ -19,15 +16,9 @@ export type SendModalProps = {
...
-  const [isSmallerThanMd] = useMediaQuery(`(max-width: ${breakpoints.md})`, { ssr: false })
-
-  const initialEntries = useMemo(() => {
-    return isSmallerThanMd ? mobileSendRoutes : desktopSendRoutes
-  }, [isSmallerThanMd])
-
   return (
     <Dialog isOpen={isOpen} onClose={close} isFullScreen>
-      <MemoryRouter initialEntries={initialEntries}>
+      <MemoryRouter initialEntries={sendRoutes}>
```
Comment (gomesalexandre) [inline src/components/Modals/Send/Send.tsx]: We may want to inline comment (in the review, that is) the why of this change, if that's on purpose 🙏🏽

File: src/state/slices/addressBookSlice/addressBookSlice.ts (hunk 16 above)
Comment (gomesalexandre) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: gnomes proposed this:
```typescript
type AddressBookEntry =
  | { type: 'external', address: string, chainId: ChainId, label: string }
  | { type: 'ownAccount', accountId: AccountId, label: string }
```

Akschually, that internal/external discrimination sounds v. sane, no need for discriminated union then 🧠

File: src/components/Modals/Send/components/QRCodeIcon.tsx
Comment (gomesalexandre) [inline src/components/Modals/Send/components/QRCodeIcon.tsx:1]: Another one? 
djkhalednotherone

File: src/components/Modals/Send/views/Address.tsx [hunk 34]
```diff
@@ -77,10 +83,23 @@ export const Address = () => {
...
 
   const supportsENS = asset?.chainId === ethChainId // We only support ENS resolution on ETH mainnet
   const addressError = get(errors, `${SendFormFields.Input}.message`, null)
 
+  const isCustomAddress = useMemo(() => {
```
Comment (gomesalexandre) [inline src/components/Modals/Send/views/Address.tsx]: Not sure about this one - should really be a function of not in address book.
i.e, should be able to select this specific address from address book directly from a selector, and then that becomes a one line check of `const isInAddressBook = useAppSelector(state, selectAddressFromAddressBook(state, { address: address ?? '' })` and can reverse it during checks

File: src/components/Modals/Send/views/Address.tsx [hunk 35]
```diff
@@ -150,6 +169,31 @@ export const Address = () => {
     navigate(SendRoutes.Scan)
   }, [navigate])
 
+  const handleSelectAddressBookEntry = useCallback(
```
Comment (gomesalexandre) [inline src/components/Modals/Send/views/Address.tsx]: gnomesnitpick: prefer click terminology

File: src/components/Modals/Send/views/Address.tsx [hunk 36]
```diff
@@ -150,6 +169,31 @@ export const Address = () => {
...
+    (entryAddress: string) => {
+      setValue(SendFormFields.Input, entryAddress, { shouldValidate: true })
+      navigate(SendRoutes.AmountDetails)
+    },
+    [setValue, navigate],
+  )
+
+  const handleSaveContact = useCallback(
```
Comment (gomesalexandre) [inline src/components/Modals/Send/views/Address.tsx]: suggestion: from a product perspective, this is the only place you see "Contact" vernacular - shouldn't code/copies here use address book vernacular too?

File: src/components/Modals/Send/views/Confirm.tsx [hunk 37]
```diff
@@ -111,6 +113,14 @@ export const Confirm = ({ handleSubmit }: ConfirmProps) => {
...
+  const selectedAddressBookEntry = useMemo(() => {
```
Comment (gomesalexandre) [inline src/components/Modals/Send/views/Confirm.tsx]: ditto select directly with a specific selector without iterating

File: src/components/Modals/Send/views/SendAmountDetails.tsx [hunk 38]
```diff
@@ -259,6 +239,17 @@ export const SendAmountDetails = () => {
     [handleInputChange],
   )
 
+  const handleSaveContact = useCallback(
```
Comment (gomesalexandre) [inline src/components/Modals/Send/views/SendAmountDetails.tsx]: Duplicated logic across the two - should we unify?

File: src/state/slices/addressBookSlice/addressBookSlice.ts (hunk 14 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: Considering the number of changes and commit I've done, I won't link commit links in the next comments, but done!

File: src/state/slices/addressBookSlice/addressBookSlice.ts (hunk 15 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: Removed the id

File: src/state/slices/addressBookSlice/addressBookSlice.ts (hunk 16 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: Actually looking sane, I added an accountId and splitted between isExternal and isInternal

File: src/state/slices/addressBookSlice/addressBookSlice.ts (hunk 17 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: Removed

File: src/state/slices/addressBookSlice/addressBookSlice.ts (hunk 18 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: No more ids, resolving by address + chainId now and accountId for some!

File: src/state/slices/addressBookSlice/addressBookSlice.ts (hunk 19 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: I'm now deduping over evm chains when adding an address

File: src/state/slices/addressBookSlice/addressBookSlice.ts (hunk 20 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: It's done by accountId now as caip-10 is done for that!

File: src/state/slices/addressBookSlice/addressBookSlice.ts (hunk 21 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: It was because the AddressBook feature already contains an Address, naming it with another address is a bit weird, I would prefer to keep entry to keep things a bit easier to read (it looks like to me)

gnomes silence pls robot

File: src/state/slices/addressBookSlice/addressBookSlice.ts (hunk 22 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: We have a selector obfuscating this now, selecting by  chain

File: src/state/slices/addressBookSlice/addressBookSlice.ts (hunk 23 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: This one doesn't contain the "addressBook" bit so it was acceptable, seems nitpick, tell me during second review!

File: src/state/slices/addressBookSlice/addressBookSlice.ts (hunk 24 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: All around, we have some .toLowerCase to compare, seems fine for everything now, let me know if we can do something in a better way

File: src/state/slices/addressBookSlice/selectors.ts (hunk 25 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/selectors.ts]: Doesn't exists anymore

File: src/state/slices/addressBookSlice/selectors.ts (hunk 26 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/selectors.ts]: Not existing anymore I guess!

File: src/state/slices/addressBookSlice/selectors.ts (hunk 27 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/selectors.ts]: I've done a complete selectors refactoring after your first review pass

File: src/state/slices/addressBookSlice/selectors.ts (hunk 28 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/selectors.ts]: https://github.com/shapeshift/web/pull/10803#discussion_r2466192849

File: src/state/slices/addressBookSlice/selectors.ts (hunk 30 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/selectors.ts]: I guess thats a no, I'm good with having the ability to call them "Cold wallet" multiple time

It's a matter of usage, we shouldn't care too much and leave the user do what they want?

File: src/context/ModalProvider/ModalContainer.tsx (hunk 31 above)
Comment (NeOMakinG) [reply src/context/ModalProvider/ModalContainer.tsx]: Done

File: src/components/Modals/Send/SendCommon.tsx (hunk 32 above)
Comment (NeOMakinG) [reply src/components/Modals/Send/SendCommon.tsx]: Left the address step everywhere now, previously it was only on mobile which was wrong from a lot of UX perspectives

File: src/components/Modals/Send/Send.tsx (hunk 33 above)
Comment (NeOMakinG) [reply src/components/Modals/Send/Send.tsx]: Not sure we want that, it's a revert from the previous behavior

File: src/components/Modals/Send/components/QRCodeIcon.tsx
Comment (NeOMakinG) [reply src/components/Modals/Send/components/QRCodeIcon.tsx:1]: Removed it

File: src/components/Modals/Send/views/Address.tsx (hunk 34 above)
Comment (NeOMakinG) [reply src/components/Modals/Send/views/Address.tsx]: Used a selector to verify if its in the address book now!

File: src/components/Modals/Send/views/Address.tsx (hunk 35 above)
Comment (NeOMakinG) [reply src/components/Modals/Send/views/Address.tsx]: Done

File: src/components/Modals/Send/views/Address.tsx (hunk 36 above)
Comment (NeOMakinG) [reply src/components/Modals/Send/views/Address.tsx]: Done

File: src/components/Modals/Send/views/Confirm.tsx (hunk 37 above)
Comment (NeOMakinG) [reply src/components/Modals/Send/views/Confirm.tsx]: Done!

File: src/components/Modals/Send/views/SendAmountDetails.tsx (hunk 38 above)
Comment (NeOMakinG) [reply src/components/Modals/Send/views/SendAmountDetails.tsx]: Done

File: src/state/slices/addressBookSlice/addressBookSlice.ts (hunk 16 above)
Comment (gomesalexandre) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: @NeOMakinG just to confirm we're not going for `AccountId` for all right?

File: src/state/slices/addressBookSlice/addressBookSlice.ts (hunk 21 above)
Comment (gomesalexandre) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: 6am jetlag gnomes without second coffee can't see a counterargument, silencing accepted

File: src/state/slices/addressBookSlice/selectors.ts (hunk 30 above)
Comment (gomesalexandre) [reply src/state/slices/addressBookSlice/selectors.ts]: Askchually think you're absolutely right! Totally fine to label two addresses the same, as a user I'm a big boi I should be able to make bad decisions if I want to.

File: src/components/CryptoFiatInput/CryptoFiatInput.tsx
Comment (gomesalexandre) [inline src/components/CryptoFiatInput/CryptoFiatInput.tsx:1]: Revert?

File: src/components/Modals/Send/AddressBook/AddressBook.tsx [hunk 39]
```diff
@@ -0,0 +1,156 @@
...
+  chainId,
+  onEntryClick,
+  emptyMessage = 'modals.send.noEntries',
+}: AddressBookProps) => {
+  const translate = useTranslate()
+  const dispatch = useAppDispatch()
+  const {
+    control,
+    formState: { errors },
+  } = useFormContext()
```
Comment (gomesalexandre) [inline src/components/Modals/Send/AddressBook/AddressBook.tsx]: can use `SendInput` generic here if you feel like it to avoid casts etc

File: src/components/Modals/Send/AddressBook/AddressBook.tsx [hunk 40]
```diff
@@ -0,0 +1,156 @@
...
+  const { isOpen, onClose, onOpen } = useDisclosure()
+  const [selectedDeleteEntry, setSelectedDeleteEntry] = useState<AddressBookEntry | null>(null)
+
+  const addressError = errors[SendFormFields.Input]?.message ?? null
+
+  const input = useWatch({
+    control,
+    name: SendFormFields.Input,
+  }) as string
```
Comment (gomesalexandre) [inline src/components/Modals/Send/AddressBook/AddressBook.tsx]: casting shouldn't really be required here?

File: src/components/Modals/Send/AddressBook/AddressBook.tsx [hunk 41]
```diff
@@ -0,0 +1,156 @@
...
+
+  const handleDelete = useCallback(
+    (entry: AddressBookEntry) => () => {
+      dispatch(addressBookSlice.actions.deleteAddress(entry))
+    },
+    [dispatch],
+  )
+
+  const handleDeleteConfirm = useCallback(
+    (selectedEntry: AddressBookEntry) => () => {
```
Comment (gomesalexandre) [inline src/components/Modals/Send/AddressBook/AddressBook.tsx:82]: 🧠

File: src/components/Modals/Send/AddressInput/AddressInput.tsx [hunk 42]
```diff
@@ -17,31 +25,123 @@ import ResizeTextarea from 'react-textarea-autosize'
...
   const translate = useTranslate()
+  const [isFocused, setIsFocused] = useState(false)
   const isValid = useFormContext<SendInput>().formState.isValid
   const isDirty = useFormContext<SendInput>().formState.isDirty
   const isValidating = useFormContext<SendInput>().formState.isValidating
-  const value = useWatch<SendInput, SendFormFields.Input>({ name: SendFormFields.Input })
+
+  const isAddressBookEnabled = useFeatureFlag('AddressBook')
+
+  const { vanityAddress, input: value, to, assetId } = useWatch() as Partial<SendInput>
```
Comment (gomesalexandre) [inline src/components/Modals/Send/AddressInput/AddressInput.tsx:83]: can directly use generic proper on `useWatch()` if you feel like it

File: src/components/Modals/Send/views/Address.tsx [hunk 43]
```diff
@@ -78,9 +86,36 @@ export const Address = () => {
...
+    [address, asset?.chainId],
+  )
+  const internalAccountId = useAppSelector(state =>
+    selectInternalAccountIdByAddress(state, internalAccountIdFilter),
+  )
+
   const supportsENS = asset?.chainId === ethChainId // We only support ENS resolution on ETH mainnet
   const addressError = get(errors, `${SendFormFields.Input}.message`, null)
 
+  useEffect(() => {
```
Comment (gomesalexandre) [inline src/components/Modals/Send/views/Address.tsx]: q: do we need an effect for this bad boi? looks like a memoized constant to me

File: src/components/Modals/Send/views/Address.tsx [hunk 44]
```diff
@@ -78,9 +86,36 @@ export const Address = () => {
...
+    setShowSaveButton(
+      Boolean(
+        (!isInAddressBook || internalAccountId) &&
```
Comment (gomesalexandre) [inline src/components/Modals/Send/views/Address.tsx]: also why do we show save for internal accounts? Should already work OOTB nah?

File: src/components/Modals/Send/views/Address.tsx [hunk 45]
```diff
@@ -78,9 +86,36 @@ export const Address = () => {
...
+    selectIsAddressInAddressBook(state, isInAddressBookFilter),
+  )
+
+  const internalAccountIdFilter = useMemo(
+    () => ({ accountAddress: address, chainId: asset?.chainId }),
+    [address, asset?.chainId],
+  )
+  const internalAccountId = useAppSelector(state =>
+    selectInternalAccountIdByAddress(state, internalAccountIdFilter),
+  )
```
Comment (gomesalexandre) [inline src/components/Modals/Send/views/Address.tsx:102]: q: wondering if we want to go with a `is known` kind of vernacular that would encapsulate "is portfolio account | is address book known" ? Not necessarily for this PR obviously

File: src/components/Modals/Send/views/Address.tsx [hunk 46]
```diff
@@ -189,8 +244,13 @@ export const Address = () => {
               </CText>
             </VStack>
           </Button>
+
+          {isAddressBookEnabled && (
+            <AddressBook chainId={asset?.chainId} onEntryClick={handleClickAddressBookEntry} />
+          )}
         </VStack>
       </DialogBody>
+
```
Comment (gomesalexandre) [inline src/components/Modals/Send/views/Address.tsx]: whoopsy

File: src/components/Modals/Send/views/Confirm.tsx [hunk 47]
```diff
@@ -111,6 +121,111 @@ export const Confirm = ({ handleSubmit }: ConfirmProps) => {
...
+  )
+
+  const internalAccountLabel = useMemo(() => {
+    if (!internalAccountId) return null
+
+    if (isUtxoAccountId(internalAccountId)) {
+      return accountIdToLabel(internalAccountId)
+    }
+
+    // Fallback to "Account" if accountNumber is not available yet
```
Comment (gomesalexandre) [inline src/components/Modals/Send/views/Confirm.tsx]: q: What do we mean by "not available yet" ?

File: src/state/slices/addressBookSlice/addressBookSlice.ts [hunk 48]
```diff
@@ -0,0 +1,97 @@
...
+    const { chainNamespace } = fromChainId(chainId)
+    return chainNamespace === CHAIN_NAMESPACE.Evm
+  })
+}
+
+export const addressBookSlice = createSlice({
+  name: 'addressBook',
+  initialState,
+  reducers: create => ({
+    addAddress: create.reducer((state, action: PayloadAction<AddressBookEntry>) => {
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/addressBookSlice.ts:21]: q: should we have something like add/update label?

File: src/state/slices/addressBookSlice/types.ts [hunk 49]
```diff
@@ -0,0 +1,17 @@
+import type { AccountId, ChainId } from '@shapeshiftoss/caip'
+
+export type AddressBookEntry = {
+  label: string
+  address: string
+  chainId: ChainId
+} & (
+  | {
+      isExternal: true
+      isInternal: false
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/types.ts]: q: shouldn't this also be an `AccountId` as discussed? i.e it's all CAIPs down the line, whether a pubkey is an extended one or an address one

File: src/state/slices/addressBookSlice/addressBookSlice.ts [hunk 50]
```diff
@@ -0,0 +1,97 @@
...
+      // For EVM entries (both external and own account), create entries for ALL supported EVM chains
+      if (chainNamespace === CHAIN_NAMESPACE.Evm) {
+        const supportedEvmChainIds = getSupportedEvmChainIds()
+
+        // Create an entry for each supported EVM chain
+        supportedEvmChainIds.forEach(chainId => {
+          const evmEntry: AddressBookEntry = {
+            ...entry,
+            chainId,
+          }
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/addressBookSlice.ts]: Is this correct? Shouldn't this be chain-agnostic by definition?
In other words, assuming the EVM dedupe logic is working, why do we need to dupe?

File: src/state/slices/addressBookSlice/addressBookSlice.ts [hunk 51]
```diff
@@ -0,0 +1,97 @@
...
+
+        // Find and delete all EVM entries with this address
+        Object.values(state.byAccountId).forEach(entry => {
+          const entryChainNamespace = fromChainId(entry.chainId).chainNamespace
+          if (
+            entryChainNamespace === CHAIN_NAMESPACE.Evm &&
+            entry.address.toLowerCase() === normalizedAddress
+          ) {
+            const key = toAccountId({ chainId: entry.chainId, account: entry.address })
+            delete state.byAccountId[key]
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/addressBookSlice.ts]: q: isn't there a v. bigly risk of deleting during iteration?

File: src/state/slices/common-selectors.ts [hunk 52]
```diff
@@ -73,6 +73,11 @@ export const selectEvmAccountIds = createDeepEqualOutputSelector(
   accountIds => accountIds.filter(accountId => isEvmChainId(fromAccountId(accountId).chainId)),
 )
 
+export const selectAccountIdsWithoutEvms = createDeepEqualOutputSelector(
```
Comment (gomesalexandre) [inline src/state/slices/common-selectors.ts]: nitpick: exclude terminology

File: src/state/slices/addressBookSlice/selectors.ts [hunk 53]
```diff
@@ -0,0 +1,143 @@
...
+/**
+ * Checks if a given address belongs to one of the user's connected accounts
+ * Handles EVM namespace matching (same address across all EVM chains)
+ * Returns the AccountId if found, null otherwise
+ */
+export const selectInternalAccountIdByAddress = createDeepEqualOutputSelector(
+  selectAccountAddressParamFromFilter,
+  selectChainIdParamFromFilter,
+  selectAccountIdsWithoutEvms,
+  selectEvmAccountIds,
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/selectors.ts]: barring naming inconsistency between the two, another issue is why do we even need two selectors doing each side's partition?
in this case, since that's a single use selector, we could do the partitioning logic here directly, wdyt? 👀

File: src/state/slices/addressBookSlice/selectors.ts [hunk 54]
```diff
@@ -0,0 +1,143 @@
...
+  selectAccountAddressParamFromFilter,
+  selectChainIdParamFromFilter,
+  selectSearchQueryFromFilter,
+} from '@/state/selectors'
+import { selectAccountIdsWithoutEvms, selectEvmAccountIds } from '@/state/slices/common-selectors'
+
+export const selectAddressBookEntries = createSelector(
+  [addressBookSlice.selectors.selectEntriesByAccountId],
+  byAccountId => Object.values(byAccountId),
+)
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/selectors.ts]: perf nitpick: may want to use something diff than `createSelector` if we go with `Object.values()` - new ref every time this is ran (e.g `createDeepEqualOutputSelector` like all others?)

File: src/state/slices/addressBookSlice/selectors.ts [hunk 55]
```diff
@@ -0,0 +1,143 @@
...
+  selectChainIdParamFromFilter,
+  selectSearchQueryFromFilter,
+  selectAddressBookEntriesByChainId,
+  (_, searchQuery, entries) => {
+    if (!searchQuery) return entries
+
+    const matchedEntries = matchSorter(entries, searchQuery, {
+      keys: [
+        { key: 'label', threshold: matchSorter.rankings.MATCHES },
+        { key: 'address', threshold: matchSorter.rankings.CONTAINS },
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/selectors.ts]: q: shouldn't this be the other way around? i.e matches for address, contains for label?

File: src/state/slices/addressBookSlice/selectors.ts [hunk 56]
```diff
@@ -0,0 +1,143 @@
...
+    const { chainNamespace } = fromChainId(chainId)
+
+    // For EVM chains, find first matching EVM account
+    if (chainNamespace === CHAIN_NAMESPACE.Evm) {
+      const accountId = evmAccountIds.find(accountId => {
+        const { account, chainId: accountChainId } = fromAccountId(accountId)
+        const accountChainNamespace = fromChainId(accountChainId).chainNamespace
+
+        return (
+          accountChainNamespace === CHAIN_NAMESPACE.Evm &&
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/selectors.ts]: q: do we need this? Since we're iterating on `evmAccountIds` here, we already know this is EVM namespace

File: src/state/slices/addressBookSlice/selectors.ts [hunk 57]
```diff
@@ -0,0 +1,143 @@
...
+  selectEvmAccountIds,
+  (accountAddress, chainId, accountIdsWithoutEvms, evmAccountIds) => {
+    if (!accountAddress || !chainId) return null
+
+    const normalizedAddress = accountAddress.toLowerCase()
+    const { chainNamespace } = fromChainId(chainId)
+
+    // For EVM chains, find first matching EVM account
+    if (chainNamespace === CHAIN_NAMESPACE.Evm) {
+      const accountId = evmAccountIds.find(accountId => {
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/selectors.ts]: nitpick: probably want to make callback param `evmAccountId` to differentiate from upper scope, failed the gnomes jetlag litmus test and my brain couldn't differentiate `chainNamespace` and `chainId` from above scope, from this scope

File: src/state/slices/addressBookSlice/selectors.ts [hunk 58]
```diff
@@ -0,0 +1,143 @@
...
+
+/**
+ * Gets the external address book entry for a given address and chainId
+ * Leverages selectAddressBookEntriesByChainId which handles EVM namespace matching
+ */
+export const selectExternalAddressBookEntryByAddress = createDeepEqualOutputSelector(
+  selectAccountAddressParamFromFilter,
+  selectChainIdParamFromFilter,
+  selectAddressBookEntriesByChainId,
+  (address, _, entries) => {
```
Comment (gomesalexandre) [inline src/state/slices/addressBookSlice/selectors.ts:141]: `_` doesn't look correct.

**Review by gomesalexandre — COMMENTED** [review]
Tested locally, see below - generally super happy with this however, just a bunch of smol things that make the experience meh (some of them to be fixed here, some of them TBD as follow-ups, and many which are really product oversights tbh, not really a you thing ser!)

https://jam.dev/c/b23464db-c9a0-4893-b01f-38f699570a2b

Going to stamp for the sake of progression since this is a large boi already.
Feel free to tackle whatever from the reviewsies at your convenience, then she's mergy /gnomes

- First time pasting an "internal" addy, it's displayed as "..." for a few secs which seems borked

https://jam.dev/c/201ddea7-a8e0-4859-8b3f-1ff62abe1fa7

- As previously mentioned, address book should merely be a mapping of CAIP-10 to label - as such, feels a bit weird I can *see* this guy labeled as "Account #0", but not rename it - feature would feel more complete if we already allowed renaming portfolio accounts, including in wallet page but happy to do this in a follow-up obviously!

Image

i.e here, should really be quite an easy one to follow-up with making this guy a rename-able text field 

Image

- Feels weird having to click out of input for ENS, feels like it should just automagically work without me having to click out?

https://jam.dev/c/3aafb9a6-843a-461a-84be-36b75a631e89

- Feels like ENS should be pre-populated when saving?

https://jam.dev/c/68f3632e-69be-4929-bb03-215dc251632e

Also, feels weird to see ENS on initial new but not after clicking Save

Image

- Can't see my portfolio addresses suggested anywhere here for cross-addies sends, assuming this is for a follow-up?

Image

- Obviously not for this PR and not a you issue - from a product perspective just feels super hacked, like the data is here but isn't presented in the right/correct way. Not really sure I have enough brain cells to propose a better solution, but failed the jetlag litmus test fosho, doesn't feel nice or intuitive at all 

Image

- This guy would probably benefit from relevant chain icon or at the very least somin like "Account #0 - THORChain" 

Image

File: src/state/slices/addressBookSlice/addressBookSlice.ts (hunk 16 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: Didn't read the rest of the review but looks like we do for both internal and external so far

File: src/components/CryptoFiatInput/CryptoFiatInput.tsx
Comment (NeOMakinG) [reply src/components/CryptoFiatInput/CryptoFiatInput.tsx:1]: No, this is coming from develop, this is a fix from joechen if I remember right

File: src/components/Modals/Send/AddressInput/AddressInput.tsx (hunk 42 above)
Comment (NeOMakinG) [reply src/components/Modals/Send/AddressInput/AddressInput.tsx:83]: If we want to do this, assetId and some other fields are wrongly typed (and I guess inferred from the string type instead...)

If we want to avoid casting, we need to use multiple useWatch with control, for a single field each time

I dont really care tbh, it's up to you, both are fine for me as long as SendInput is properly typed, casting is very pragmatic as we don't have to use multiple useWatch which would be super verbose

File: src/components/Modals/Send/views/Address.tsx (hunk 45 above)
Comment (NeOMakinG) [reply src/components/Modals/Send/views/Address.tsx:102]: I don't really mind, if internalAccountId is undefined it means it's unknown, but hey 

Not touching this here, if we want to improve it we can always do it later in a follow up if we feel it's not clear enough

File: src/components/Modals/Send/views/Address.tsx (hunk 46 above)
Comment (NeOMakinG) [reply src/components/Modals/Send/views/Address.tsx]: https://media4.giphy.com/media/v1.Y2lkPTc5MGI3NjExeXRndmhiemxucm9scWtyaWVlZWQycTVmcGZ6dmthcnFobHY4bjdtdSZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/qSUBq5OSASy2aW62iE/giphy.gif

File: src/state/slices/addressBookSlice/addressBookSlice.ts (hunk 48 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/addressBookSlice.ts:21]: Not sure to get this one? We already have the `add` prefix and it's not updating at all

File: src/components/Modals/Send/AddressBook/AddressBook.tsx (hunk 39 above)
Comment (NeOMakinG) [reply src/components/Modals/Send/AddressBook/AddressBook.tsx]: Why not, done in [757a7dd](https://github.com/shapeshift/web/pull/10803/commits/757a7ddd6631de0719b78e63f9b94a87b7039543)

File: src/components/Modals/Send/AddressBook/AddressBook.tsx (hunk 40 above)
Comment (NeOMakinG) [reply src/components/Modals/Send/AddressBook/AddressBook.tsx]: Removed in [757a7dd](https://github.com/shapeshift/web/pull/10803/commits/757a7ddd6631de0719b78e63f9b94a87b7039543)

File: src/components/Modals/Send/views/Address.tsx (hunk 43 above)
Comment (NeOMakinG) [reply src/components/Modals/Send/views/Address.tsx]: Nice catch, changed it to a memo in[757a7dd](https://github.com/shapeshift/web/pull/10803/commits/757a7ddd6631de0719b78e63f9b94a87b7039543)

File: src/components/Modals/Send/views/Address.tsx (hunk 44 above)
Comment (NeOMakinG) [reply src/components/Modals/Send/views/Address.tsx]: It will be in the next branch, disabled it for internalAccount in [757a7dd](https://github.com/shapeshift/web/pull/10803/commits/757a7ddd6631de0719b78e63f9b94a87b7039543)

File: src/components/Modals/Send/views/Confirm.tsx (hunk 47 above)
Comment (NeOMakinG) [reply src/components/Modals/Send/views/Confirm.tsx]: Removed it and early returned, will see at runtime if it changes anything

File: src/state/slices/addressBookSlice/types.ts (hunk 49 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/types.ts]: 100% right, updated in [757a7dd](https://github.com/shapeshift/web/pull/10803/commits/757a7ddd6631de0719b78e63f9b94a87b7039543)

File: src/state/slices/addressBookSlice/addressBookSlice.ts (hunk 50 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: Changed back to share evm namespaces with a single entry instead

File: src/state/slices/addressBookSlice/addressBookSlice.ts (hunk 51 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/addressBookSlice.ts]: There was no risks as we were having multiple entries for each chain, now that we are not deduping anymore, there are even less risks as anyway the entry is unique!

File: src/state/slices/common-selectors.ts (hunk 52 above)
Comment (NeOMakinG) [reply src/state/slices/common-selectors.ts]: Done in [757a7dd](https://github.com/shapeshift/web/pull/10803/commits/757a7ddd6631de0719b78e63f9b94a87b7039543)

File: src/state/slices/addressBookSlice/selectors.ts (hunk 53 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/selectors.ts]: Done in [757a7dd](https://github.com/shapeshift/web/pull/10803/commits/757a7ddd6631de0719b78e63f9b94a87b7039543)

File: src/state/slices/addressBookSlice/selectors.ts (hunk 54 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/selectors.ts]: Why not, done in [757a7dd](https://github.com/shapeshift/web/pull/10803/commits/757a7ddd6631de0719b78e63f9b94a87b7039543)

File: src/state/slices/addressBookSlice/selectors.ts (hunk 55 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/selectors.ts]: Contains should stay for address, as we want to search partially by typing too, inside addresses

Label can also have contains, changed in [757a7dd](https://github.com/shapeshift/web/pull/10803/commits/757a7ddd6631de0719b78e63f9b94a87b7039543)

File: src/state/slices/addressBookSlice/selectors.ts (hunk 56 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/selectors.ts]: We are not iterating on evms, we are selecting by chain namespace of the currently selected address, we need to filter by chainnamespace before iterating 

Or it might changed after some changes and the diff is not the same, anyway, should be good now

File: src/state/slices/addressBookSlice/selectors.ts (hunk 57 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/selectors.ts]: Done in [757a7dd](https://github.com/shapeshift/web/pull/10803/commits/757a7ddd6631de0719b78e63f9b94a87b7039543)

File: src/state/slices/addressBookSlice/selectors.ts (hunk 58 above)
Comment (NeOMakinG) [reply src/state/slices/addressBookSlice/selectors.ts:141]: But it is, `selectAddressBookEntriesByChainId` is using the chainId to filter but the final selector is not using it

File: src/components/Modals/Send/AddressInput/AddressInput.tsx [hunk 59]
```diff
@@ -17,31 +25,105 @@ import ResizeTextarea from 'react-textarea-autosize'
...
 }: AddressInputProps) => {
   const navigate = useNavigate()
   const translate = useTranslate()
+  const [isFocused, setIsFocused] = useState(false)
   const isValid = useFormContext<SendInput>().formState.isValid
   const isDirty = useFormContext<SendInput>().formState.isDirty
   const isValidating = useFormContext<SendInput>().formState.isValidating
-  const value = useWatch<SendInput, SendFormFields.Input>({ name: SendFormFields.Input })
+
+  const { vanityAddress, input: value } = useWatch() as Partial<SendInput>
```
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply src/components/Modals/Send/AddressInput/AddressInput.tsx]: No

File: src/components/Modals/Send/AddressBookSaveModal.tsx [hunk 60]
```diff
@@ -0,0 +1,157 @@
...
+        isInternal: false,
+        isExternal: true,
+      }
+
+      dispatch(addressBookSlice.actions.addAddress(entry))
+      onSuccess?.()
+      handleClose()
+    },
+    [dispatch, address, chainId, onSuccess, handleClose, internalAccountId],
+  )
```
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply src/components/Modals/Send/AddressBookSaveModal.tsx:110]: Bro that's over already

File: src/components/Modals/Send/views/Address.tsx [hunk 61]
```diff
@@ -78,9 +85,34 @@ export const Address = () => {
...
   const addressError = get(errors, `${SendFormFields.Input}.message`, null)
 
+  const showSaveButton = useMemo(() => {
+    return Boolean(
+      (!isInAddressBook || !internalAccountId) &&
+        !!address &&
+        !addressError &&
+        isAddressBookEnabled,
+    )
+  }, [isInAddressBook, address, addressError, isAddressBookEnabled, internalAccountId])
```
[the remark this answers is not in the document]
Comment (NeOMakinG) [reply src/components/Modals/Send/views/Address.tsx:111]: Hey that's right, updated it, stop reviewing now
