### PR TITLE
fix: mobile wallet loading and error handling

### LINKED ISSUE #9648: Loading spinner on opening wallet
We need a proper loading state for selecting and opening a wallet. And a sanity check on android specifically. 

If it's better to just finish [SS-4522](https://linear.app/shapeshift-dao/issue/SS-4522/remember-last-wallet-and-wallet-quality-of-life) in one pass that is preferred. 

[https://discord.com/channels/554694662431178782/1375109664563400795](https://discord.com/channels/554694662431178782/1375109664563400795)

### PR DESCRIPTION
**Pull request by NeOMakinG**
## Description

- Adding 2 more mobile loading states: one when selecting wallet, disabling others wallet selection, the other when we wait for the wallet to redirect to the dashboard
- Also handle the biometrics cancelling, if the user was cancelling it it was impossible to select a wallet anymore

## Issue (if applicable)

closes #9648

## Risk
Low
> High Risk PRs Require 2 approvals

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

## Testing
- Go on mobile app (you can use the expo PR to test easily)
- Try to select a wallet, you should see proper loading states
- Cancelling the biometric shouldn't make it errored anymore but just show the wallet list
- Showing the loading needs a fresh app launching, or maybe changing the select app and coming back to the app, not 100% reproducible tbh as sometime it's very fast

### Engineering
n/a

### Operations
n/a
- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)

https://github.com/user-attachments/assets/447af488-1b0b-4ab2-9e01-e63f9b89af5d

https://github.com/user-attachments/assets/25237f81-f00a-4eeb-b1ad-dbed4d97a749

### CODE REVIEW

File: src/components/MobileWalletDialog/routes/SavedWallets.tsx [hunk 1]
```diff
@@ -160,7 +160,7 @@ export const SavedWallets: React.FC<SavedWalletsProps> = ({ onClose }) => {
         </DialogHeaderRight>
       </DialogHeader>
       <DialogBody>
-        <MobileWallestList
```
Comment (gomesalexandre) [inline src/components/MobileWalletDialog/routes/SavedWallets.tsx:163]: 💀

File: src/pages/ConnectWallet/components/WalletList.tsx [hunk 2]
```diff
@@ -121,40 +144,42 @@ export const MobileWallestList: React.FC<MobileWalletDialogProps> = ({
...
-              onRename={handleRename}
-              onDelete={handleDelete}
-              _hover={_hover}
-              _active={_active}
-            />
-          )
-        })}
-      </Stack>
+      <>
+        {error ? (
```
Comment (gomesalexandre) [inline src/pages/ConnectWallet/components/WalletList.tsx:149]: 💜
