### PR TITLE
fix: remove content flash when switching tabs on wallet mobile

### LINKED ISSUE #10104: Squash content rerenders on tab switching
## Context

There is a content flash of the new “Add crypto” button when changing onto the “Home” screen.

### Reproduction and AC \[Author\]

Smash trough the tabs and you should see content flash. 

## Screenshots, video  \[Author\]

[Screen Recording Jul 25 2025 (1).mov](https://uploads.linear.app/ed5193d7-27ef-4be2-b461-c7791d75bc4f/0b622af1-3af7-445a-b0e3-1481cd7dbe7d/5e3ed064-cf90-4afe-a17c-4bc220289b33?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2VkNTE5M2Q3LTI3ZWYtNGJlMi1iNDYxLWM3NzkxZDc1YmM0Zi8wYjYyMmFmMS0zYWY3LTQ0NWEtYjBlMy0xNDgxY2Q3ZGJlN2QvNWUzZWQwNjQtY2Y5MC00YWZlLWExN2MtNGJjMjIwMjg5YjMzIiwiaWF0IjoxNzUzNDY0NDcyLCJleHAiOjMzMzI0MDI0NDcyfQ.UIWKo7-7ZpScN8Vwi9Tl4UIWFHCvJ0MDCGSSIDyP2gQ)

## Rough how to fix \[Eng\]

> Breakdown a path to solve for acc or any reference material, docs. A place for estimation notes or initial comments for solutions.

### PR DESCRIPTION
**Pull request by premiumjibles**
## Description

Fixes content flash when flicking to wallet asset infinite scroll

## Issue (if applicable)

closes #10104 

## Risk

Low

> High Risk PRs Require 2 approvals

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

## Testing

This slightly adjusts the logic of `useInfiniteScroll`. Which is used in a few spots, test them.
* Scrollable transaction history list in My Wallet > Activity
* Markets Table
* AccountsTable in My Wallet > Wallet

### Engineering

:point_up: 

### Operations

:point_up: 

- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)

After change - https://jam.dev/c/142984e6-50f6-4bef-a487-66365b869fd7

Prd - https://jam.dev/c/9a36abe1-bf1b-4983-8405-c78f6c65ec50

## Summary by CodeRabbit

* **Refactor**
  * Improved performance and simplified logic for infinite scroll functionality. No changes to user-facing behavior.

### CODE REVIEW

File: src/hooks/useInfiniteScroll/useInfiniteScroll.tsx [hunk 1]
```diff
@@ -14,23 +14,15 @@ export const useInfiniteScroll = <T extends any>({
   isScrollable = false,
 }: UseInfiniteScrollProps<T>) => {
   const [amount, setAmount] = useState(initialTxsCount ?? defaultAmount)
-  const [, startTransition] = useTransition()
-
-  const [rawData, setRawData] = useState<T[]>([])
-
-  useEffect(() => {
```
Comment (premiumjibles) [inline src/hooks/useInfiniteScroll/useInfiniteScroll.tsx:21]: This is what was causing the flash. Initialising the `data` array to empty fed through an empty array to the subscriber which immediately renders an empty state. This useEffect directly follows up by filling the array and that rerenders with the actual data.

This adjustment ensures the first render contains data if it's available.

**Review by 0xApotheosis — APPROVED** [review]
Does the thing! Tested on both wallets with and without assets with balances to ensure the placeholder still works as expected.
