### PR TITLE
fix: remove earn tab

### LINKED ISSUE #8989: Opportunities (Earn tab)
Are sad, bye bye carousel.

### PR DESCRIPTION
**Pull request by NeOMakinG**
## Description

Remove earn tab, this is not removing slices and asset page components as our users should be able to unstake from FOX opportunities, we couldn't even be able to remove them as the evergreen contract still exists, a better cleanup would be to be able to remove any stale slices + out of date opportunities handlers

But see this PR as a first step until we take a product decision on the next steps

- Also add the earn tab to the mobile dashboard
- Clean the dashboard header as it's now not redirecting to the earn page

## Issue (if applicable)

closes #8989

## Risk

> High Risk PRs Require 2 approvals

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

## Testing
- Earn tab shouldn't be shown anywhere
- Fox ecosystem page should replace earn page in the mobile app
- But opportunities are shown on asset pages, so user can stake them
- FOX evergreen in fox ecosystem page works as intended

### Engineering
na

### Operations
n/a
- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)
image
image
image
image

### CODE REVIEW

File: src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Deposit.tsx [hunk 1]
```diff
@@ -257,16 +254,6 @@ export const Deposit: React.FC<DepositProps> = ({
...
-  const handleBack = useCallback(() => {
-    history.push({
-      pathname: `/defi/earn`,
-      search: qs.stringify({
-        ...query,
-        modal: DefiAction.Overview,
-      }),
-    })
-  }, [history, query])
-
```
Comment (gomesalexandre) [inline src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Deposit.tsx:269]: q: what will be the back behaviour now that this is rm'd?

**Review by gomesalexandre — CHANGES_REQUESTED** [review]
DeFi tab is now borkeroo'd
image

File: src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Deposit.tsx (hunk 1 above)
Comment (NeOMakinG) [reply src/features/defi/providers/fox-farming/components/FoxFarmingManager/Deposit/components/Deposit.tsx:269]: We don't have any back behavior on these modals, handleBack was not consumed it was dead code

**Comment by NeOMakinG** [comment]
> DeFi tab is now borkeroo'd image

I'm dumb, my bad, should be good now I reverted a lot of things considering we didn't want to ditch the whole dashboard but just the routing

File: src/components/StakingVaults/DeFiEarn.tsx [hunk 2]
```diff
@@ -19,7 +19,6 @@ type DefiEarnProps = {
   positionTableProps?: Omit<PositionTableProps, 'searchQuery'>
   includeEarnBalances?: boolean
   includeRewardsBalances?: boolean
-  header?: JSX.Element
```
Comment (gomesalexandre) [inline src/components/StakingVaults/DeFiEarn.tsx:22]: blocking: we still need this 
Screenshot 2025-03-24 at 20 19 06

File: src/assets/translations/en/main.json [hunk 3]
```diff
@@ -513,8 +513,6 @@
     "noAccountsOpportunities": "You have no accounts for this asset, so staking opportunities are currently unavailable.",
     "clickHereToEarn": "Click here to earn %{apr} APR* by farming your ETH-FOX liquidity pool tokens",
     "overview": "Overview",
-    "myPositions": "My Positions",
-    "myPositionsBody": "A list of your currently active positions in DeFi.",
```
Comment (gomesalexandre) [inline src/assets/translations/en/main.json:517]: blocking: revert me

File: src/pages/Dashboard/DashboardSidebar.tsx [hunk 4]
```diff
@@ -64,7 +63,6 @@ export const DashboardSidebar = memo(() => {
   return (
     <Flex width='full' flexDir='column' gap={6}>
       <PromoCard data={promoData} />
-      <EligibleCarousel />
```
Comment (gomesalexandre) [inline src/pages/Dashboard/DashboardSidebar.tsx:67]: q: have we confirmed this goes away as well?

File: src/pages/Dashboard/EarnDashboard.tsx [hunk 5]
```diff
@@ -1,44 +1,28 @@
...
-          colorScheme='purple'
-          variant='ghost'
-          as={NavLink}
-          to='/earn'
-          size='sm'
-          ml='auto'
-          rightIcon={arrowForwardIcon}
-        >
-          {translate('defi.viewAllPositions')}
-        </Button>
```
Comment (gomesalexandre) [inline src/pages/Dashboard/EarnDashboard.tsx:33]: blocking: this should go away, but we should keep the heading and subheading

**Review by gomesalexandre — CHANGES_REQUESTED** [review]
LGTM minus the DeFi header being gone:

- Display of wallet DeFi positions:

https://jam.dev/c/9f9f6329-b733-41e3-833a-dffe3a4aa147

- Managing DeFi positions

https://jam.dev/c/bb38a27f-ff0b-4be8-b978-24e3a1ec3add

File: src/components/StakingVaults/DeFiEarn.tsx (hunk 2 above)
Comment (NeOMakinG) [reply src/components/StakingVaults/DeFiEarn.tsx]: Done in [8db94c1](https://github.com/shapeshift/web/pull/9086/commits/8db94c1ebd64971e4a6f3dd422478112132f863f)

File: src/assets/translations/en/main.json (hunk 3 above)
Comment (NeOMakinG) [reply src/assets/translations/en/main.json]: Done in [8db94c1](https://github.com/shapeshift/web/pull/9086/commits/8db94c1ebd64971e4a6f3dd422478112132f863f)

File: src/pages/Dashboard/DashboardSidebar.tsx (hunk 4 above)
Comment (NeOMakinG) [reply src/pages/Dashboard/DashboardSidebar.tsx:67]: Yes in private

File: src/pages/Dashboard/EarnDashboard.tsx (hunk 5 above)
Comment (NeOMakinG) [reply src/pages/Dashboard/EarnDashboard.tsx:33]: Done in [8db94c1](https://github.com/shapeshift/web/pull/9086/commits/8db94c1ebd64971e4a6f3dd422478112132f863f)

**Review by gomesalexandre — APPROVED** [review]
fuark yeah

image
