### PR TITLE
fix: ensure generic transaction query invalidation doesnt over invalidate or silently fail

### LINKED ISSUE #10113: Fix generic transaction subscriber cache invalidation over-invalidation + silent crashes
# Summary

We've recently been moving to replace loading status screens with less intrusive toasts and action centre cards that update in the background as an action progresses. When thing finish loading, we often have to invalidate some kind of data to get re-fetched. 

Our current solution for that can be found in `useGenericTransactionSubscriber`. The solution being to basically invalidate all data that could have potentially been updated by an action. 

This has two problems:

1. **Over-invalidation:** We're invalidating all generic transaction queries on any completion, even unrelated ones.
2. **Silent crashes:** Query key functions expect specific parameter content for their transaction type. When RFOX functions run during TCY transactions with TCY-specific data, they crash silently and skip invalidations (see screenshot)

# Steps to reproduce

* Try doing a fox farming transaction and check the console for errors

## AC

* No more silent crashes
* Only invalidate relevant data to a given action

### PR DESCRIPTION
**Pull request by premiumjibles**
## Description

Currently our logic for cache invalidation after complete pending actions in the action center only works for rFox transactions. Example here of the logic dying in the background on a TCY transaction.

image

This change adds the idea of a "queryId" to the generic transactions which represents what query data we want to invalidate. This prevent over invalidation or crashes caused by invalidating query keys that don't make sense for a given transaction.

## Issue (if applicable)

closes #10113 

## Risk

Low 

> High Risk PRs Require 2 approvals

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

## Testing

* Test that TCY staking and unstaking updates the balance
* Test that rFox staking and unstaking updates the balance
* Ensure no errors pop up in the console like the one in the description during a TCY or rFox stake

### Operations

- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)

https://jam.dev/c/a0338d6e-8897-4b35-83f8-70dbe38a0a02

## Summary by CodeRabbit

* **New Features**
  * Improved transaction processing by introducing targeted updates for staking and unstaking activities, resulting in more efficient data refreshes for RFOX and TCY assets.

* **Refactor**
  * Simplified how staking data is refreshed by removing unnecessary dependencies and streamlining query logic.

* **Chores**
  * Added new metadata fields to support more precise transaction tracking and updates.

### CODE REVIEW

File: src/state/slices/actionSlice/types.ts [hunk 1]
```diff
@@ -69,8 +69,14 @@ export enum GenericTransactionDisplayType {
...
 }
 
+export enum GenericTransactionQueryId {
+  RFOX = 'rFOX',
+  TCY = 'TCY',
+}
+
 type ActionGenericTransactionMetadata = {
   displayType: GenericTransactionDisplayType
+  queryId?: GenericTransactionQueryId
```
Comment (premiumjibles) [inline src/state/slices/actionSlice/types.ts:79]: We technically have the option of avoiding introducing this and instead invalidating based off the displayType. We probably shouldn't though. These are two different concerns and it might bite us in the but later if we tie them together.

File: src/pages/TCY/queries/useTcyStaker.tsx [hunk 2]
```diff
@@ -2,36 +2,19 @@ import type { AccountId } from '@shapeshiftoss/caip'
...
-        action.transactionMetadata.displayType === GenericTransactionDisplayType.TCY &&
-        [ActionType.Withdraw, ActionType.Deposit].includes(action.type) &&
-        action.status === ActionStatus.Complete,
-    ).length
-  }, [allGenericActions])
+export const getTcyStakerQueryKey = (accountId: AccountId | undefined) => ['tcy-staker', accountId]
 
+export const useTcyStaker = (accountId: AccountId | undefined) => {
   return useSuspenseQuery({
-    queryKey: ['tcy-staker', accountId, completeTcyStakingActionCount],
```
Comment (premiumjibles) [inline src/pages/TCY/queries/useTcyStaker.tsx:34]: This was here before to ensure our balance updated on successful stake. I've aligned it with our current pattern.

**Review by 0xApotheosis — APPROVED** [review]
Looking solid.

✅ Test that TCY staking and unstaking updates the balance
✅ Test that rFox staking and unstaking updates the balance
✅ Ensure no errors pop up in the console like the one in the description during a TCY or rFox stake
