### PR TITLE
fix: show market cap instead of price for market cap category

### LINKED ISSUE #10861: Display Market Cap instead of Current price for Market Cap on Markets Page.
## Context \[Author\]

Instead of displaying price for the Market Cap section of the Markets Page, we should display the Market Cap of the top assets.

### Reproduction \[Author\]

*Display asset market cap for the top market cap assets instead of the current price.* 

### AC

<br>Change what is displayed from the current price to the current market cap. 

## Rough how to fix \[Eng\]

> Breakdown a path to solve for acc or any reference material, docs. A place for estimation notes or initial comments for solutions.

### PR DESCRIPTION
**Pull request by JoeChenJ**
## Description
Show market cap instead of price in the Market Cap section on /explore page

## Issue (if applicable)

closes #10861

## Risk

> High Risk PRs Require 2 approvals

No risk

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

## Testing

- Make sure the Market Cap section on /explore page shows market cap instead of price

### Operations

- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)
c189636ebc94a83bd1ab4f1e839a6294

## Summary by CodeRabbit

* **New Features**
  * Added optional market capitalization display for asset rows.
  * Asset rows can now show market cap instead of price when appropriate.
  * The Explore category view toggles between price and market cap display for MarketCap categories.

* **Chores**
  * Rendering logic updated to ensure correct display when market cap is enabled.

### CODE REVIEW

File: src/pages/Explore/components/CategoryCard.tsx [hunk 1]
```diff
@@ -204,6 +204,24 @@ export const CategoryCard = memo(
...
+                index={index}
+                style={emptyStyle}
+                color={assetTitleColor}
+                showMarketCap
+              />
+            ))}
+          </Flex>
+        )
+      }
+
```
Comment (NeOMakinG) [inline src/pages/Explore/components/CategoryCard.tsx]: We probably only need to toggle showPrice and showMarketCap depending on the category instead of early returning the whole JSX?

**Review by NeOMakinG — APPROVED** [review]
image

Only one small comment that is quite nitpick but I would love to have it fixed before getting this in as it will feel a bit cleaner

File: src/pages/Explore/components/CategoryCard.tsx (hunk 1 above)
Comment (JoeChenJ) [reply src/pages/Explore/components/CategoryCard.tsx]: Absolutely, fixed in https://github.com/shapeshift/web/pull/10870/commits/c6837614d17ab6679c6ccfb978b1ade8fbc613d5
