### PR TITLE
fix: migrate on chain suffix generation at runtime

### LINKED ISSUE #10416: Use related assets keys to show "on Chain" suffix
I found quite a high priority issue: <br>We are using asset names to generate "on X" suffix for any assets, while we are not 100% sure they are related, it might be a scam token<br><br>`generateAssetData` is simply verifying that the asset as the same name and applying "on X" chain in the end of the name<br><br>AC:

* "on X" suffix is removed
* Later we will add it back only on grouped assets

### PR DESCRIPTION
**Pull request by NeOMakinG**
## Description

We were weirdly adding on chain suffix based on strict equality of asset name instead of relying on related asset ids

This PR remove this generation in favor of a runtime build of the asset names, using a helper and a JSX component to add the `on X` suffix depending of the asset and related assets, if the `relatedAssetKey` is different from the current asset, we can assume it's on another chain than the primary asset

## Issue (if applicable)

closes #10416

## Risk

> High Risk PRs Require 2 approvals

> What protocols, transaction types, wallets or contract interactions might be affected by this PR?

## Testing
Smoke test the whole app, everywhere it's useful to show asset chain in the name, we should display it
- Global search
- Trade search
- Market page
- Asset details page
- Notice some assets doesn't have it, it's because they are not in the related asset notion which means we will probably need to find a new provider to improve the way we are linking related assets
- Anywhere!

### Operations

- [ ] :checkered_flag: My feature is behind a flag and doesn't require operations testing (yet)

## Screenshots (if applicable)
https://jam.dev/c/9f0fecb6-4a86-48d9-8bfe-5acbb2b527d6

## Summary by CodeRabbit

- Style
  - Simplified asset names across the app (e.g., “FOX”, “USD Coin”) by removing network suffixes.
  - PositionTable no longer displays the “on [Network]” text; shows name and symbol only.

- Chores
  - Updated token color mappings across multiple networks.
  - Refreshed related-asset relationships data index for improved associations.
  - Added a new state migration to clear assets (version 178).

- Tests
  - Updated swapper and helper test fixtures to reflect simplified asset names.

### CODE REVIEW

File: scripts/generateAssetData/generateAssetData.ts [hunk 1]
```diff
@@ -89,28 +81,6 @@ const generateAssetData = async () => {
...
-
-  const isNotUniqueAsset = (asset: Asset) => {
-    const { chainId } = fromAssetId(asset.assetId)
-    return Object.entries(evmAssetNamesByChainId)
-      .reduce<string[]>((prev, [_chainId, assetNames]) => {
-        if (chainId === _chainId) return prev
-        return prev.concat(assetNames)
-      }, [])
-      .includes(asset.name)
-  }
```
Comment (gomesalexandre) [inline scripts/generateAssetData/generateAssetData.ts:112]: Oh boi 👋🏽  she won't be missed

File: src/assets/translations/en/main.json [hunk 2]
```diff
@@ -14,6 +14,7 @@
     "next": "Next",
     "edit": "Edit",
     "error": "Error",
+    "assetOnChain": "%{assetName} on %{chainName}",
```
Comment (gomesalexandre) [inline src/assets/translations/en/main.json]: And now i18n friendly too 🎉

File: src/components/AccountCard.tsx [hunk 3]
```diff
@@ -80,19 +81,18 @@ export const AccountCard = ({
           asset.icons ? leftMultipleIconBoxSize : leftIconBoxSize
         } - var(--chakra-sizes-${rightIconBoxSize}))`}
       >
-        <Tooltip label={asset.name} isDisabled={!willOverflow}>
+        <Tooltip label={buildAssetTitle(asset, translate)} isDisabled={!willOverflow}>
```
Comment (gomesalexandre) [inline src/components/AccountCard.tsx]: q @NeOMakinG: do we need to call a runtime method everywhere we have asset names? Looks like we would easily forget to do so.
Couldn't we make the `Asset` in store `Asset & {nameWithNetwork: string}` in the store when upserting asset/s and have this called just once and be present across the board?

File: src/components/AssetName/AssetName.tsx [hunk 4]
```diff
@@ -0,0 +1,72 @@
...
+    return translate('common.assetOnChain', {
+      assetName: asset.name,
+      chainName: chainIdToChainDisplayName(asset.chainId),
+    })
+  }
+
+  return asset.name
+}
+
+export const AssetName = ({
```
Comment (gomesalexandre) [inline src/components/AssetName/AssetName.tsx]: Same here - do we need an explicit component just to display this? i.e, if we have it in the asset in store, then that diff could also be reverted

File: src/components/StakingVaults/PositionTable.tsx [hunk 5]
```diff
@@ -40,21 +40,12 @@ const initialState = { pageSize: 30 }
...
     <Flex alignItems='center' gap={4}>
       <AssetIcon size='sm' assetId={assetId} key={assetId} />
       <Flex flexDir='column'>
-        <RawText>
-          {asset.name} {`(${asset.symbol})`}
-        </RawText>
-        {networkName !== asset.name ? (
-          <RawText variant='sub-text' size='xs'>
-            {`on ${networkName}`}
-          </RawText>
```
Comment (gomesalexandre) [inline src/components/StakingVaults/PositionTable.tsx:56]: 💜

File: src/lib/translate.ts
Comment (gomesalexandre) [inline src/lib/translate.ts:1]: q: do we need this ? can't we use `ReturnType typeof useTranslate` with `useTranslate` from `node_modules/react-polyglot/src/useTranslate.d.ts` ? 

Also aware `TranslateFunction` is any in .d.ts, but we should fix the root cause (e.g by shadowing `react-polyglot` types), not add this hack

Comment (gomesalexandre) [reply src/lib/translate.ts:1]: https://github.com/shapeshift/web/pull/10428

**Review by gomesalexandre — CHANGES_REQUESTED** [review]
LGTM high-level but strong preference for avoiding that runtime util and having optional "Asset on chain" as an additional property in store 

Also one spotted bug re: double `on <chain>` for FOX:

image

@NeOMakinG we need to remove hardcoded 'on xyz' suffixes in `scripts/generateAssetData/overrides.ts` i.e:

https://github.com/shapeshift/web/blob/4c7acaac825c48706ba50c3fb20ec5e36f02feba/scripts/generateAssetData/overrides.ts#L11

File: src/components/AccountCard.tsx (hunk 3 above)
Comment (NeOMakinG) [reply src/components/AccountCard.tsx]: Removed that to add at runtime instead!

File: src/components/AssetName/AssetName.tsx (hunk 4 above)
Comment (NeOMakinG) [reply src/components/AssetName/AssetName.tsx]: Nop, removed it to add at runtime

File: src/lib/translate.ts
Comment (NeOMakinG) [reply src/lib/translate.ts:1]: It's not existing anymore

File: src/lib/asset-service/service/localAssetData.ts [hunk 6]
```diff
@@ -6,5 +6,6 @@ import encodedRelatedAssetIndex from './encodedRelatedAssetIndex.json'
 
 export const { assetData: localAssetData, sortedAssetIds } = decodeAssetData(
   encodedAssetData as unknown as EncodedAssetData,
+  true,
```
Comment (gomesalexandre) [inline src/lib/asset-service/service/localAssetData.ts:9]: ey, I guess that works!

**Review by gomesalexandre — APPROVED** [review]
Tested again locally , LGTM now! https://jam.dev/c/6155d7e1-c8b4-45b9-a3c8-73f30aac5a5d

Also did a lil regression test against develop and confirmed looking gucci too 🤌

File: scripts/generateAssetData/color-map.json [hunk 7]
```diff
@@ -265,6 +264,7 @@
   "eip155:1/erc20:0x09fa04aac9c6d1c6131352ee950cd67ecc6d4fb9": "#ECE4D2",
   "eip155:1/erc20:0x09fd37d9aa613789c517e76df1c53aece2b60df4": "#F6F5EE",
   "eip155:1/erc20:0x0a13a5929e5f0ff0eaba4bd9e9512c91fce40280": "#185578",
+  "eip155:1/erc20:0x0a26c80be4e060e688d7c23addb92cbb5d2c9eca": "#3ECCBE",
   "eip155:1/erc20:0x0a26e7ab5c554232314a8d459eff0ede72333f08": "#D5EAFC",
   "eip155:1/erc20:0x0a27c31f087cd3d30cdad339731bede4194531a4": "#079277",
   "eip155:1/erc20:0x0a2a015a15a8e019abc386fee88b8a6d7a0d90df": "#121A1A",
```
[the remark this answers is not in the document]
Comment (gomesalexandre) [reply scripts/generateAssetData/color-map.json:270]: meh

File: src/components/TradeAssetSearch/components/GroupedAssetList/components/GroupedAssetRow.tsx [hunk 8]
```diff
@@ -166,17 +166,16 @@
...
               textOverflow='ellipsis'
               whiteSpace='nowrap'
               maxWidth='200px'
               overflow='hidden'
               fontWeight='semibold'
               color='text.base'
-            >
-              {asset.name}
-            </Text>
+            />
```
[the remark this answers is not in the document]
Comment (gomesalexandre) [reply src/components/TradeAssetSearch/components/GroupedAssetList/components/GroupedAssetRow.tsx]: stale

File: src/components/TradeAssetSearch/components/GroupedAssetList/components/GroupedAssetRow.tsx [hunk 9]
```diff
@@ -7,6 +7,7 @@ import { useTranslate } from 'react-polyglot'
 
 import { Amount } from '@/components/Amount/Amount'
 import { AssetIcon } from '@/components/AssetIcon'
+import { AssetName } from '@/components/AssetName/AssetName'
```
[the remark this answers is not in the document]
Comment (gomesalexandre) [reply src/components/TradeAssetSearch/components/GroupedAssetList/components/GroupedAssetRow.tsx]: stale

File: src/components/TradeAssetSearch/components/CustomAssetAcknowledgement.tsx [hunk 10]
```diff
@@ -19,6 +19,7 @@ import { useTranslate } from 'react-polyglot'
 
 import { WarningAcknowledgement } from '@/components/Acknowledgement/WarningAcknowledgement'
 import { AssetIcon } from '@/components/AssetIcon'
+import { AssetName } from '@/components/AssetName/AssetName'
```
[the remark this answers is not in the document]
Comment (gomesalexandre) [reply src/components/TradeAssetSearch/components/CustomAssetAcknowledgement.tsx]: stale

File: src/components/AssetName/AssetName.tsx [hunk 11]
```diff
@@ -0,0 +1,72 @@
...
+import { selectAssets } from '@/state/slices/selectors'
+import { useAppSelector } from '@/state/store'
+
+type AssetNameProps = {
+  assetId: AssetId
+  postFix?: string
+  showAssetSymbol?: boolean
+  ref?: React.RefObject<HTMLDivElement>
+} & TextProps
+
```
[the remark this answers is not in the document]
Comment (gomesalexandre) [reply src/components/AssetName/AssetName.tsx]: stale
